<a href="https://colab.research.google.com/github/avinandhajs/Judge_It_Well/blob/main/Copy_of_Assignment_0(Basic_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
##Q.1.1
import numpy as np
array1 = np.array([0]*10)
print(array1)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
##Q.1.2
array2 = np.array([5]*10)
print(array2)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
##Q.1.3
array3 = np.arange(9).reshape(3, 3)
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
##Q.1.4
number = np.random.rand()
print(number)

0.005900763927835673


In [ ]:
##Q.1.5
array4 = np.linspace(0, 1, 20, endpoint=False)
print(array4)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [ ]:
##Q.1.6
n_of_vowel = 0
s = input("ENTER THE STRING : ")
for letter in s.lower():
  if letter in ['a','e','i','o','u']:
    n_of_vowel += 1
print(n_of_vowel)

ENTER THE STRING : Watermelon
4


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##Q.2.1
import numpy as np
numbers = np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even_num = numbers[numbers%2 == 0]
print(even_num)

[ 12  44 102  -8  56  90 -24  48]


In [ ]:
##Q.2.2
array5 =  np.random.randint(10,100,(5,4))
print(array2)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
##Q.2.3
#taking the 3X3 matrix from the Q.1.3
matrix = array3
array6 = matrix[0:3,0:2]
print(array6)

[[0 1]
 [3 4]
 [6 7]]


In [ ]:
##Q.2.4
array7 = np.random.randint(0,100,20) # 1D array
array7 = array7.reshape(4,5) #reshaped into 2D array
print(array7)

[[27 12 73 69 71]
 [ 2  9  6 69 81]
 [29 17  2 39 68]
 [81 44 41 25 43]]


In [ ]:
##Q.2.5
#let array7 be our 2D array from the previous question
array8 = array7.reshape(1,20)
print(array8)

[[27 12 73 69 71  2  9  6 69 81 29 17  2 39 68 81 44 41 25 43]]


In [ ]:
##Q.2.6
matrix1 = np.random.randint(0,100,9).reshape(3,3)
matrix2 = np.random.randint(0,100,15).reshape(3,5)
matrix3 = np.array([0]*15).reshape(3,5)
for i in range(0,3):
  for j in range(0,5):
    for k in range(0,3):
      matrix3[i][j] = matrix3[i][j] + (matrix1[i][k])*(matrix2[k][j])
print(matrix1)
print(matrix2)
print(matrix3)

[[40 22 46]
 [59 61 66]
 [ 3 44 55]]
[[33 69 18 34  9]
 [53 41 77 37 67]
 [66 99  4 74 30]]
[[ 5522  8216  2598  5578  3214]
 [ 9536 13106  6023  9147  6598]
 [ 6061  7456  3662  5800  4625]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
##Q.3.(i)
rol1,col1 = matrix1.shape
rol2,col2 = matrix2.shape
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


(ii) Using loops (without using numpy)

In [ ]:
##Q.3.(ii)
col1 = 0
rol2 = 0
for ele in matrix1[0]:
  col1 += 1
for ele in matrix2:
  rol2 += 1
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


**Q.4**
(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [ ]:
##Q.4.1
s = 0
X = [1,2,3,4,5]
for i in X:
  s += i
meanx = s/len(X)
print(f"The mean of X is = {meanx}")

The mean of X is = 3.0


In [ ]:
##Q.4.2
s = 0
y = [2,4,5,4,5]
for i in y:
  s += i
meany = s/len(y)
print(f"The mean of X is = {meany}")

The mean of X is = 4.0


In [ ]:
##Q.4.3
# let m be the slope
cf1 = ([0]*100)
y = [2,4,5,4,5]
X = [1,2,3,4,5]
num = den = 0
for i in range(0,5):
  num += (meanx - X[i])*(meany - y[i])
  den += (meanx - X[i])**2
m = num/den
print(f"Slope is = {m}")

Slope is = 0.6


In [ ]:
#Q.4.4
c = meany - m * meanx
print(f"The y intercept = {c}")

The y intercept = 2.2


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [6]:
import pandas as pd
df = pd.read_csv('performance_dataset.csv') # reading the dataset

In [11]:
#2
df.head(5)

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [10]:
#2
df.tail(6)

hours_studied  attendance_percent  parent_education  internet_access  \
4994       4.826182           84.737572               3.0              0.0   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
4994          2.0                   1.0            0.0       2.0   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
4994          11.971699               1.0  ...           11.709831   
4995          26.632876               0.0  ...           15.530375   
4996          13.090832               4.0  ...            9.113572   
4997          27.700626               3.0  ...           16.549603   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
4994  167.442375  33.571682         1.0         1.0            0.0   
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0            NaN   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
4994              3.0            5.361889                  2.0      1.0  
4995              1.0            6.146414                  2.0      0.0  
4996              2.0            6.044880                  2.0      1.0  
4997              1.0            7.852906                  NaN      1.0  
4998              2.0            9.503284                  2.0      1.0  
4999              1.0            6.292816                  1.0      1.0  

[6 rows x 25 columns]

In [19]:
#3
#renamed a column
df = df.rename(columns={'hours_studied': 'time_spent'})
df.head()

time_spent  attendance_percent  parent_education  internet_access  \
0    4.743108           79.781453               3.0              NaN   
1   10.992036           97.666558               3.0              1.0   
2    8.848935           57.950598               2.0              0.0   
3    3.481116           84.636899               0.0              0.0   
4    6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [27]:
#4
#it is similair to slicing in python
df.iloc[3:5,2:5] # 3rd and 4th row, from 2 nd to 4 th column

parent_education  internet_access  school_type
3               0.0              0.0          0.0
4               1.0              0.0          0.0

In [45]:
#5
df.fillna('-', inplace=True)  #replacing NaN with '-'
df.head()

hours_studied attendance_percent parent_education internet_access  \
0      4.743108          79.781453              3.0               -   
1     10.992036          97.666558              3.0             1.0   
2      8.848935          57.950598              2.0             0.0   
3      3.481116          84.636899              0.0             0.0   
4      6.264199          58.081774              1.0             0.0   

  school_type sports_participation part_time_job siblings commute_time_mins  \
0           -                  1.0           0.0      4.0         31.681382   
1         0.0                  3.0             -      1.0         19.423883   
2         0.0                  1.0           0.0      3.0         28.859972   
3         0.0                  2.0           0.0      4.0         40.083853   
4         0.0                  3.0           1.0      2.0          23.83882   

  favorite_subject  ... screen_time_weekly   height_cm  weight_kg lunch_type  \
0              2.0  ...           2.339672  157.398274  53.055261        0.0   
1              4.0  ...                  -  151.295654  60.628213        2.0   
2              0.0  ...          16.989369   183.90064  65.655529        0.0   
3              1.0  ...          11.631093   164.83557  38.357323        2.0   
4              2.0  ...          15.372885  166.303604  39.271753          -   

  math_tutor reading_habit video_game_freq music_hours_weekly  \
0          -           1.0             0.0           0.898032   
1        1.0           1.0             3.0           3.291397   
2        1.0           0.0             1.0                0.0   
3        1.0           2.0             1.0           2.410233   
4        0.0           1.0             2.0           1.200275   

  parent_meeting_freq uniform  
0                 1.0     1.0  
1                 0.0     0.0  
2                 2.0     1.0  
3                 0.0     0.0  
4                 1.0     1.0  

[5 rows x 25 columns]

In [65]:
#6
df = pd.read_csv('performance_dataset.csv')
df.drop(3, inplace=True)
df.head(6)

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
4       6.264199           58.081774               1.0              0.0   
5      12.954310           66.696510               3.0              0.0   
6       0.719962           60.457167               2.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
4          0.0                   3.0            1.0       2.0   
5          1.0                   3.0            1.0       1.0   
6          NaN                   0.0            1.0       0.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
4          23.838820               2.0  ...           15.372885  166.303604   
5          37.296292               0.0  ...           14.535370  176.745495   
6                NaN               4.0  ...            7.893048  146.213152   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   
5  64.342675         2.0         1.0            2.0              2.0   
6  68.420398         2.0         1.0            3.0              1.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
4            1.200275                  1.0      1.0  
5            6.485664                  2.0      NaN  
6            7.476785                  0.0      0.0  

[6 rows x 25 columns]

In [72]:
#7
df.filter(regex='^a') #colomns starting with letter a

attendance_percent
0              79.781453
1              97.666558
2              57.950598
4              58.081774
5              66.696510
...                  ...
4995           66.031236
4996           54.031024
4997           67.916004
4998           83.729465
4999           89.559193

[4999 rows x 1 columns]

In [75]:
#8
#combining two column to make a new column
df = pd.read_csv('performance_dataset.csv')
#calculating BMI (body mass index)
df['BMI'] = df.weight_kg / ((df.height_cm)/100)**2
df.head()

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...   height_cm  weight_kg  \
0          31.681382               2.0  ...  157.398274  53.055261   
1          19.423883               4.0  ...  151.295654  60.628213   
2          28.859972               0.0  ...  183.900640  65.655529   
3          40.083853               1.0  ...  164.835570  38.357323   
4          23.838820               2.0  ...  166.303604  39.271753   

   lunch_type  math_tutor  reading_habit  video_game_freq  music_hours_weekly  \
0         0.0         NaN            1.0              0.0            0.898032   
1         2.0         1.0            1.0              3.0            3.291397   
2         0.0         1.0            0.0              1.0            0.000000   
3         2.0         1.0            2.0              1.0            2.410233   
4         NaN         0.0            1.0              2.0            1.200275   

   parent_meeting_freq  uniform        BMI  
0                  1.0      1.0  21.415515  
1                  0.0      0.0  26.486335  
2                  2.0      1.0  19.413544  
3                  0.0      0.0  14.117130  
4                  1.0      1.0  14.199628  

[5 rows x 26 columns]