**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [2]:
# Q 1.1

arr_zeroes = [0]*10
print(arr_zeroes)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [3]:
# Q 1.2

arr_fives = [5]*10
print(arr_fives)



[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [8]:
# Q 1.3

rng = np.random.default_rng()
mat =rng.integers(0,9,(3,3))
print(mat)

[[2 8 2]
 [8 3 3]
 [3 1 6]]


In [12]:
# Q 1.4

rng = np.random.default_rng()
x =rng.integers(0,2)
print(x)

0


In [15]:
# Q 1.5

rng = np.random.default_rng()
x=rng.integers(0,2,(20))
print(x)

[0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 1]


In [20]:
# Q 1.6

string = str(input("ENTER A STRING : "));
vowels = ['a','e','i','o','u']
count = 0
for i in string:
  if i in vowels:
    count+=1
print(count)




ENTER A STRING : sdfghj
0


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [21]:
# Q 2.1

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
for i in numbers:
  if i%2==0:
    print(i,end=' ')

12 44 102 -8 56 90 -24 48 

In [22]:
# Q 2.2

nrg = np.random.default_rng()
arr = nrg.integers(10,100,(5,4))
print(arr)



[[89 54 89 67]
 [85 90 81 50]
 [26 80 73 81]
 [32 83 41 15]
 [19 31 93 69]]


In [24]:
# Q 2.3

arr_new = arr[0:3,0:2]
print(arr_new)

[[89 54]
 [85 90]
 [26 80]]


In [25]:
# Q 2.4

nrg = np.random.default_rng()
x = nrg.integers(0,10,(20))
y = x.reshape(4,5)
print(y)

[[5 9 8 1 5]
 [9 8 2 8 2]
 [0 7 9 6 0]
 [1 5 6 9 3]]


In [27]:
# Q 2.5

arr_oned = y.flatten()
print(arr_oned)




[5 9 8 1 5 9 8 2 8 2 0 7 9 6 0 1 5 6 9 3]


In [61]:
# Q 2.6

rng = np.random.default_rng()
A = rng.integers(0,10,(2,2))
B = rng.integers(0,10,(2,2))

if (isvalid(2,2,2,2)):
  arr_mul = np.dot(A,B)
  print(arr_mul)



[[40 25]
 [48 32]]


**Q.3**

(i) Check if matrix multiplication is valid

In [75]:
# Q 3.1

def isvalid(x,y,p,q):
  rng = np.random.default_rng()

  A = rng.integers(0,10,(x,y))
  B = rng.integers(0,10,(p,q))
  if y!=p:
     return False
  else:
     return True

x = rng.integers(0,10)
y = rng.integers(0,10)
p = rng.integers(0,10)
q = rng.integers(0,10)



isvalid(x,y,p,q)


False

(ii) Using loops (without using numpy)

In [92]:
# Q 3.2

import random
rows1 = random.randint(1,9)
cols1 = random.randint(1,9)
matrix1 = []
for i in range(rows1):
    row1 = []
    for j in range(cols1):
        row1.append(random.randint(1,9))
    matrix1.append(row1)

rows2 = random.randint(1,9)
cols2 = random.randint(1,9)
matrix2 = []
for i in range(rows2):
    row2 = []
    for j in range(cols2):
        row2.append(random.randint(1,9))
    matrix2.append(row2)

if cols2 == rows1:
  print("matrix multiplication is valid")
else:
  print("matrix multiplication is not valid")


matrix multiplication is valid


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [77]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]

# MEAN OF X

meanX = sum(X)/len(X)
print(meanX)

3.0


In [79]:
# MEAN OF Y

X = [1,2,3,4,5]
Y = [2,4,5,4,5]

meanY = sum(Y)/len(Y)
print(meanY)

4.0


In [87]:
# SLOPE(m)

X = [1,2,3,4,5]
Y = [2,4,5,4,5]
num = 0
den = 0

for i in range(len(X)):
  num += (X[i] - meanX) * (Y[i] - meanY)
  den += (X[i] - meanX) ** 2
if (den == 0):
    print("SLOPE IS NOT DEFINED i.e.. THE LINE IS PARALLEL TO Y AXIS")
else:
    m = num / den
    print(m)

0.6


In [88]:
# INTERCEPT(b)

b = meanY - (m * meanX)
print(b)

2.2


In [89]:
# PREDICTED VALUES
4.0


4.0

##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


In [114]:
# 1

import pandas as pd
df = pd.read_csv(f"https://drive.google.com/uc?export=download&id={"1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq"}")


In [113]:
# 2.1

df.head()

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [118]:
# 2.2

df.head(16)

hours_studied  attendance_percent  parent_education  internet_access  \
0        4.743108           79.781453               3.0              NaN   
1       10.992036           97.666558               3.0              1.0   
2        8.848935           57.950598               2.0              0.0   
3        3.481116           84.636899               0.0              0.0   
4        6.264199           58.081774               1.0              0.0   
5       12.954310           66.696510               3.0              0.0   
6        0.719962           60.457167               2.0              0.0   
7        6.713262           63.990601               1.0              1.0   
8       11.797809           84.437431               3.0              1.0   
9        5.399779           76.552077               2.0              0.0   
10       5.963342           54.191108               0.0              1.0   
11       7.715873           55.539041               0.0              0.0   
12      12.474169           95.368739               3.0              1.0   
13       6.083294           51.081407               3.0              0.0   
14       6.668054           97.201280               0.0              1.0   
15       6.696946           63.161241               2.0              0.0   

    school_type  sports_participation  part_time_job  siblings  \
0           NaN                   1.0            0.0       4.0   
1           0.0                   3.0            NaN       1.0   
2           0.0                   1.0            0.0       3.0   
3           0.0                   2.0            0.0       4.0   
4           0.0                   3.0            1.0       2.0   
5           1.0                   3.0            1.0       1.0   
6           NaN                   0.0            1.0       0.0   
7           2.0                   2.0            0.0       3.0   
8           0.0                   1.0            0.0       0.0   
9           1.0                   2.0            0.0       4.0   
10          0.0                   3.0            1.0       2.0   
11          1.0                   0.0            1.0       5.0   
12          0.0                   0.0            0.0       6.0   
13          0.0                   2.0            1.0       2.0   
14          0.0                   3.0            0.0       2.0   
15          0.0                   0.0            0.0       3.0   

    commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0           31.681382               2.0  ...            2.339672  157.398274   
1           19.423883               4.0  ...                 NaN  151.295654   
2           28.859972               0.0  ...           16.989369  183.900640   
3           40.083853               1.0  ...           11.631093  164.835570   
4           23.838820               2.0  ...           15.372885  166.303604   
5           37.296292               0.0  ...           14.535370  176.745495   
6                 NaN               4.0  ...            7.893048  146.213152   
7           30.064064               2.0  ...           13.058085  166.310626   
8           15.620543               1.0  ...            8.101199  155.137833   
9           22.012151               4.0  ...           20.415948  161.578542   
10          38.159836               1.0  ...           14.096965  161.629177   
11           5.000000               1.0  ...           14.827132  156.872729   
12          29.310399               2.0  ...            7.912026  151.538063   
13          12.474610               1.0  ...           12.067095  159.410046   
14          38.720599               0.0  ...           11.285045  171.268276   
15          46.214143               2.0  ...           14.597319  165.833018   

    weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0   53.055261         0.0         NaN            1.0              0.0   
1   60.628213         2.0         1.0            1.0              3.0   
2   65.6

In [117]:
# 2.3

df.tail(20)

hours_studied  attendance_percent  parent_education  internet_access  \
4980       9.846280           79.402056               3.0              1.0   
4981      10.623076           84.784619               0.0              1.0   
4982      11.751279           84.081318               1.0              NaN   
4983       8.403378           97.183643               1.0              1.0   
4984       5.311795           68.998939               3.0              1.0   
4985       3.399616                 NaN               1.0              0.0   
4986      10.213858                 NaN               3.0              0.0   
4987      11.060641           73.310643               3.0              1.0   
4988      10.973572           83.086284               2.0              1.0   
4989       9.986863           66.934409               0.0              1.0   
4990       4.878031           59.088906               3.0              1.0   
4991      10.861546           55.723819               1.0              1.0   
4992       2.269449           91.068824               0.0              1.0   
4993      10.335344          100.000000               3.0              0.0   
4994       4.826182           84.737572               3.0              0.0   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
4980          0.0                   0.0            1.0       3.0   
4981          1.0                   NaN            1.0       4.0   
4982          NaN                   2.0            0.0       2.0   
4983          2.0                   2.0            1.0       3.0   
4984          2.0                   2.0            0.0       3.0   
4985          1.0                   0.0            NaN       1.0   
4986          0.0                   1.0            1.0       1.0   
4987          0.0                   1.0            0.0       3.0   
4988          2.0                   0.0            NaN       2.0   
4989          1.0                   0.0            0.0       0.0   
4990          2.0                   NaN            1.0       1.0   
4991          2.0                   2.0            0.0       1.0   
4992          2.0                   1.0            0.0       0.0   
4993          1.0                   3.0            0.0       2.0   
4994          2.0                   1.0            0.0       2.0   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
4980          15.978280               0.0  ...           15.432831   
4981          33.185953               0.0  ...           14.227470   
4982          33.805915               1.0  ...           15.028262   
4983          26.126382               0.0  ...            6.044226   
4984          46.809500               3.0  ...           17.707911   
4985          19.230799               1.0  ...            9.586823   
4986          26.518328               0.0  ...           15.546691   
4987           7.064656               4.0  ...            7.087335   
4988          51.871649               3.0  ...           13.627009   
4989          30.223464               0.0  ...                 NaN   
4990           7.438898               3.0  ...                 NaN   
4991          43.415955               NaN  ...           14.319683   
4992          36.444477     

In [119]:
# 2.4

df.columns

Index(['hours_studied', 'attendance_percent', 'parent_education',
       'internet_access', 'school_type', 'sports_participation',
       'part_time_job', 'siblings', 'commute_time_mins', 'favorite_subject',
       'club_member', 'self_study_hours', 'pet_count', 'locker_number',
       'bus_route', 'screen_time_weekly', 'height_cm', 'weight_kg',
       'lunch_type', 'math_tutor', 'reading_habit', 'video_game_freq',
       'music_hours_weekly', 'parent_meeting_freq', 'uniform'],
      dtype='object')

In [120]:
# 2.5

df.dtypes

hours_studied           float64
attendance_percent      float64
parent_education        float64
internet_access         float64
school_type             float64
sports_participation    float64
part_time_job           float64
siblings                float64
commute_time_mins       float64
favorite_subject        float64
club_member             float64
self_study_hours        float64
pet_count               float64
locker_number           float64
bus_route               float64
screen_time_weekly      float64
height_cm               float64
weight_kg               float64
lunch_type              float64
math_tutor              float64
reading_habit           float64
video_game_freq         float64
music_hours_weekly      float64
parent_meeting_freq     float64
uniform                 float64
dtype: object

In [121]:
# 2.6

df.describe()

hours_studied  attendance_percent  parent_education  internet_access  \
count    4750.000000         4750.000000       4750.000000      4750.000000   
mean        8.078365           74.696663          1.511579         0.503158   
std         2.948970           14.296907          1.124102         0.500043   
min         0.000000           40.000000          0.000000         0.000000   
25%         6.067024           64.666932          0.000000         0.000000   
50%         8.113447           74.893237          2.000000         1.000000   
75%        10.068370           85.104610          3.000000         1.000000   
max        18.714738          100.000000          3.000000         1.000000   

       school_type  sports_participation  part_time_job     siblings  \
count  4750.000000           4750.000000    4750.000000  4750.000000   
mean      0.993263              1.504421       0.489053     2.032000   
std       0.813627              1.111343       0.499933     1.426602   
min       0.000000              0.000000       0.000000     0.000000   
25%       0.000000              1.000000       0.000000     1.000000   
50%       1.000000              2.000000       0.000000     2.000000   
75%       2.000000              2.000000       1.000000     3.000000   
max       2.000000              3.000000       1.000000     9.000000   

       commute_time_mins  favorite_subject  ...  screen_time_weekly  \
count        4750.000000       4750.000000  ...         4750.000000   
mean           30.460856          2.004421  ...           13.902894   
std            14.357631          1.414877  ...            5.998482   
min             5.000000          0.000000  ...            0.000000   
25%            20.185850          1.000000  ...            9.899414   
50%            29.999436          2.000000  ...           13.893609   
75%            40.205028          3.000000  ...           18.027138   
max            85.268616          4.000000  ...           34.499493   

         height_cm    weight_kg   lunch_type   math_tutor  reading_habit  \
count  4750.000000  4750.000000  4750.000000  4750.000000    4750.000000   
mean    160.070126    54.852794     0.987789     0.507158       1.507789   
std      11.884900    11.902029     0.820008     0.500001       1.109428   
min     130.000000    30.000000     0.000000     0.000000       0.000000   
25%     151.927614    46.584774     0.000000     0.000000       1.000000   
50%     159.997054    54.795697     1.000000     1.000000       1.000000   
75%     168.187011    63.084992     2.000000     1.000000       3.000000   
max     200.000000    96.824370     2.000000     1.000000       3.000000   

       video_game_freq  music_hours_weekly  parent_meeting_freq      uniform  
count      4750.000000         4750.000000          4750.000000  4750.000000  
mean          1.497474            5.047120             0.999579     0.504632  
std           1.109452            2.861449             0.813913     0.500031  
min           0.000000            0.000000             0.000000     0.000000  
25%           1.000000            2.997055             0.000000     0.000000  
50%           2.000000            5.031735             1.000000     1.000000  
75%           2.000000            7.043462             2.000000     1.000000  
max           3.000000           13.983962             2.000000     1.000000  

[8 rows x 25 columns]

In [122]:
# 3.1

df.hours_studied




0        4.743108
1       10.992036
2        8.848935
3        3.481116
4        6.264199
          ...    
4995     4.633189
4996     3.744086
4997     2.420855
4998    10.741467
4999     3.938481
Name: hours_studied, Length: 5000, dtype: float64

In [123]:
# 3.2

df[['hours_studied','internet_access']]

hours_studied  internet_access
0          4.743108              NaN
1         10.992036              1.0
2          8.848935              0.0
3          3.481116              0.0
4          6.264199              0.0
...             ...              ...
4995       4.633189              1.0
4996       3.744086              0.0
4997       2.420855              0.0
4998      10.741467              NaN
4999       3.938481              0.0

[5000 rows x 2 columns]

from matplotlib import pyplot as plt
_df_0['hours_studied'].plot(kind='hist', bins=20, title='hours_studied')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['internet_access'].plot(kind='hist', bins=20, title='internet_access')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='hours_studied', y='internet_access', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['hours_studied'].plot(kind='line', figsize=(8, 4), title='hours_studied')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_4['internet_access'].plot(kind='line', figsize=(8, 4), title='internet_access')
plt.gca().spines[['top', 'right']].set_visible(False)

In [125]:
# 3.3

df.hours_studied.unique()

array([ 4.74310819, 10.99203634,  8.84893549, ...,  2.42085455,
       10.74146658,  3.93848069])

In [126]:
# 3.4

df[df['hours_studied'] == 0]

hours_studied  attendance_percent  parent_education  internet_access  \
31              0.0           82.741310               0.0              0.0   
195             0.0           77.609672               NaN              0.0   
546             0.0           84.235550               0.0              1.0   
764             0.0           86.537294               2.0              0.0   
940             0.0           87.458162               2.0              0.0   
1142            0.0           67.830398               2.0              0.0   
1580            0.0                 NaN               1.0              0.0   
1638            0.0           48.912368               2.0              NaN   
1664            0.0          100.000000               1.0              1.0   
1694            0.0           79.554689               2.0              1.0   
1950            0.0           84.918556               NaN              1.0   
2042            0.0          100.000000               2.0              1.0   
2185            0.0           74.903720               0.0              0.0   
2244            0.0           77.456528               2.0              0.0   
2546            0.0           84.358698               1.0              0.0   
4565            0.0           69.314644               3.0              0.0   
4644            0.0           74.125380               1.0              1.0   

      school_type  sports_participation  part_time_job  siblings  \
31            0.0                   2.0            1.0       2.0   
195           2.0                   0.0            0.0       2.0   
546           1.0                   3.0            1.0       1.0   
764           1.0                   1.0            1.0       1.0   
940           1.0                   NaN            0.0       0.0   
1142          0.0                   0.0            1.0       1.0   
1580          0.0                   0.0            1.0       3.0   
1638          0.0                   3.0            0.0       2.0   
1664          0.0                   3.0            0.0       1.0   
1694          2.0                   1.0            NaN       2.0   
1950          2.0                   1.0            0.0       2.0   
2042          0.0                   3.0            0.0       4.0   
2185          1.0                   0.0            1.0       0.0   
2244          2.0                   0.0            1.0       0.0   
2546          2.0                   2.0            0.0       2.0   
4565          0.0                   2.0            1.0       0.0   
4644          1.0                   1.0            1.0       2.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
31            19.436256               4.0  ...            0.000000   
195           13.306454               1.0  ...           10.887988   
546           25.802205               1.0  ...           15.742296   
764           28.313433               2.0  ...           21.019269   
940           22.403121               2.0  ...            1.980538   
1142          45.533642               4.0  ...           14.502667   
1580          19.298303               0.0  ...            8.162996   
1638          18.146837               NaN  ...           13.845135   
1664          48.396446               0.0  ...            4.923273   
1694          25.667700               2.0  ...           14.599085   
1950          47.885471               1.0  ...           10.347131   
2042          41.505223               4.0  ...           19.107075   
2185          29.838004               NaN  ...           23.072431   
2244          38.323798               1.0  ...           13.543707   
2546          27.213066               4.0  ...           22.818014   
4565          17.246068               NaN  ...           10.068408   
4644          51.150310               3.0  ...           13.638937   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
31    153.084413  69.536024         2.0      

In [127]:
# 3.5

df[(df['hours_studied']== 0) & (df['internet_access']== 0)]

hours_studied  attendance_percent  parent_education  internet_access  \
31              0.0           82.741310               0.0              0.0   
195             0.0           77.609672               NaN              0.0   
764             0.0           86.537294               2.0              0.0   
940             0.0           87.458162               2.0              0.0   
1142            0.0           67.830398               2.0              0.0   
1580            0.0                 NaN               1.0              0.0   
2185            0.0           74.903720               0.0              0.0   
2244            0.0           77.456528               2.0              0.0   
2546            0.0           84.358698               1.0              0.0   
4565            0.0           69.314644               3.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
31            0.0                   2.0            1.0       2.0   
195           2.0                   0.0            0.0       2.0   
764           1.0                   1.0            1.0       1.0   
940           1.0                   NaN            0.0       0.0   
1142          0.0                   0.0            1.0       1.0   
1580          0.0                   0.0            1.0       3.0   
2185          1.0                   0.0            1.0       0.0   
2244          2.0                   0.0            1.0       0.0   
2546          2.0                   2.0            0.0       2.0   
4565          0.0                   2.0            1.0       0.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
31            19.436256               4.0  ...            0.000000   
195           13.306454               1.0  ...           10.887988   
764           28.313433               2.0  ...           21.019269   
940           22.403121               2.0  ...            1.980538   
1142          45.533642               4.0  ...           14.502667   
1580          19.298303               0.0  ...            8.162996   
2185          29.838004               NaN  ...           23.072431   
2244          38.323798               1.0  ...           13.543707   
2546          27.213066               4.0  ...           22.818014   
4565          17.246068               NaN  ...           10.068408   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
31    153.084413  69.536024         2.0         0.0            3.0   
195   152.247248  36.328209         2.0         0.0            1.0   
764   150.446042  65.302898         NaN         1.0            2.0   
940   153.662043  30.328193         1.0         1.0            3.0   
1142  154.277382  54.739800         1.0         0.0            1.0   
1580  158.785329        NaN         0.0         0.0            0.0   
2185  162.481006  41.716484         0.0         1.0            2.0   
2244  154.307783  47.896495         2.0         0.0            3.0   
2546  174.225148  38.074066         2.0         0.0            0.0   
4565  171.268659  67.036219         NaN         NaN            1.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
31                0.0            0.000000                  2.0      NaN  
195               2.0            2.360294                  2.0      0.0  
764               3.0            3.113652                  1.0      1.0  
940               0.0            3.681268                  2.0      1.0  
1142              2.0            2.903800                  2.0      0.0  
1580              1.0            0.000000                  1.0      0.0  
2185              NaN            0.000000                  0.0      0.0  
2244              2.0            4.865779                  0.0      0.0  
2546              1.0            7.023974                  0.0      1.0  
4565              1.0            4.834606                  1.0      0.0  

[10 rows x 25 columns]

In [128]:
# 4.1

df.iloc[28]

hours_studied             7.579794
attendance_percent       74.378602
parent_education          1.000000
internet_access           1.000000
school_type               0.000000
sports_participation      0.000000
part_time_job             0.000000
siblings                  2.000000
commute_time_mins        48.796625
favorite_subject          4.000000
club_member               1.000000
self_study_hours          0.883230
pet_count                 1.000000
locker_number           397.000000
bus_route                 3.000000
screen_time_weekly       18.318074
height_cm               150.531529
weight_kg                57.496878
lunch_type                     NaN
math_tutor                     NaN
reading_habit             3.000000
video_game_freq           2.000000
music_hours_weekly        5.099779
parent_meeting_freq       2.000000
uniform                   1.000000
Name: 28, dtype: float64

In [131]:
# 4.2

df.iloc[4,7]



np.float64(2.0)

In [132]:
# 4.3

df.iloc[8,-1]

np.float64(1.0)

In [133]:
# 4.4

df.iloc[8,-1]

np.float64(1.0)

In [134]:
# 4.5

df.iloc[12:25]

hours_studied  attendance_percent  parent_education  internet_access  \
12      12.474169           95.368739               3.0              1.0   
13       6.083294           51.081407               3.0              0.0   
14       6.668054           97.201280               0.0              1.0   
15       6.696946           63.161241               2.0              0.0   
16      14.617790           75.755774               1.0              0.0   
17      14.560358           78.326656               2.0              1.0   
18      11.012162           67.779072               NaN              1.0   
19       9.158559           83.483078               1.0              1.0   
20      10.212106           71.364498               0.0              0.0   
21      12.472196           61.852777               0.0              NaN   
22       5.192498           63.081898               1.0              0.0   
23      11.527487           70.106696               3.0              0.0   
24       4.238358           98.871022               0.0              1.0   

    school_type  sports_participation  part_time_job  siblings  \
12          0.0                   0.0            0.0       6.0   
13          0.0                   2.0            1.0       2.0   
14          0.0                   3.0            0.0       2.0   
15          0.0                   0.0            0.0       3.0   
16          0.0                   1.0            NaN       2.0   
17          2.0                   2.0            0.0       NaN   
18          0.0                   1.0            0.0       0.0   
19          0.0                   0.0            0.0       1.0   
20          1.0                   2.0            0.0       1.0   
21          2.0                   3.0            1.0       2.0   
22          1.0                   0.0            1.0       2.0   
23          NaN                   0.0            0.0       3.0   
24          1.0                   2.0            0.0       NaN   

    commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
12          29.310399               2.0  ...            7.912026  151.538063   
13          12.474610               1.0  ...           12.067095  159.410046   
14          38.720599               0.0  ...           11.285045  171.268276   
15          46.214143               2.0  ...           14.597319  165.833018   
16          30.565882               0.0  ...            6.968149  164.003608   
17                NaN               0.0  ...           15.702864  138.379577   
18          21.547325               0.0  ...           25.172526  159.638602   
19          46.488135               3.0  ...            3.271151  153.518459   
20           5.000000               0.0  ...           10.201711         NaN   
21          19.337520               2.0  ...            3.403042  140.977109   
22           5.000000               3.0  ...            8.691720  170.498548   
23          46.310514               1.0  ...           17.422152  143.369641   
24          36.130234               3.0  ...            9.982128  146.562995   

    weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
12  60.879209         1.0         0.0            3.0              0.0   
13  58.070936         1.0         1.0            2.0              0.0   
14  55.194753         0.0         1.0            3.0              2.0   
15  64.914481         2.0         1.0            1.0              3.0   
16  63.399633         0.0         0.0            NaN              3.0   
17  55.654350         1.0         0.0            0.0              3.0   
18  56.976962         2.0         0.0            3.0              3.0   
19  59.360539         2.0         0.0            0.0              NaN   
20  54.848284         0.0         1.0            1.0              2.0   
21  42.683991         1.0         0.0            2.0              3.0   
22  49.815273         2.0         0.0            NaN              2.0   
23  54.963872    

In [136]:
# 5.1
# Finds the total entries with null values

df.isnull().sum().sum()

np.int64(6250)

In [137]:
# 6.1
#Drop rows with any null

df.dropna()


hours_studied  attendance_percent  parent_education  internet_access  \
3          3.481116           84.636899               0.0              0.0   
7          6.713262           63.990601               1.0              1.0   
8         11.797809           84.437431               3.0              1.0   
10         5.963342           54.191108               0.0              1.0   
12        12.474169           95.368739               3.0              1.0   
...             ...                 ...               ...              ...   
4983       8.403378           97.183643               1.0              1.0   
4984       5.311795           68.998939               3.0              1.0   
4993      10.335344          100.000000               3.0              0.0   
4994       4.826182           84.737572               3.0              0.0   
4995       4.633189           66.031236               0.0              1.0   

      school_type  sports_participation  part_time_job  siblings  \
3             0.0                   2.0            0.0       4.0   
7             2.0                   2.0            0.0       3.0   
8             0.0                   1.0            0.0       0.0   
10            0.0                   3.0            1.0       2.0   
12            0.0                   0.0            0.0       6.0   
...           ...                   ...            ...       ...   
4983          2.0                   2.0            1.0       3.0   
4984          2.0                   2.0            0.0       3.0   
4993          1.0                   3.0            0.0       2.0   
4994          2.0                   1.0            0.0       2.0   
4995          2.0                   3.0            1.0       3.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
3             40.083853               1.0  ...           11.631093   
7             30.064064               2.0  ...           13.058085   
8             15.620543               1.0  ...            8.101199   
10            38.159836               1.0  ...           14.096965   
12            29.310399               2.0  ...            7.912026   
...                 ...               ...  ...                 ...   
4983          26.126382               0.0  ...            6.044226   
4984          46.809500               3.0  ...           17.707911   
4993          58.279255               4.0  ...           21.269810   
4994          11.971699               1.0  ...           11.709831   
4995          26.632876               0.0  ...           15.530375   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
3     164.835570  38.357323         2.0         1.0            2.0   
7     166.310626  65.876931         2.0         1.0            0.0   
8     155.137833  46.922817         0.0         1.0            1.0   
10    161.629177  42.016934         2.0         0.0            3.0   
12    151.538063  60.879209         1.0         0.0            3.0   
...          ...        ...         ...         ...            ...   
4983  147.275008  39.025787         2.0         1.0            0.0   
4984  166.628282  54.986474         1.0         0.0            3.0   
4993  165.948164  40.170458         2.0         1.0            0.0   
4994  167.442375  33.571682         1.0         1.0            0.0   
4995  160.210764  60.125200         2.0         0.0            2.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
3                 1.0            2.410233                  0.0      0.0  
7                 0.0           12.024411                  2.0      1.0  
8                 1.0            5.892455                  2.0      1.0  
10                2.0            6.570614                  1.0      0.0  
12                0.0            2.903802                  0.0      1.0  
...               ...                 ...                  ...      ...  
4983              2.0            6.354001           

In [138]:
# 6.2
#Drop rows with all null

df.dropna(how='all')

hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
0             NaN                   1.0            0.0       4.0   
1             0.0                   3.0            NaN       1.0   
2             0.0                   1.0            0.0       3.0   
3             0.0                   2.0            0.0       4.0   
4             0.0                   3.0            1.0       2.0   
...           ...                   ...            ...       ...   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
0             31.681382               2.0  ...            2.339672   
1             19.423883               4.0  ...                 NaN   
2             28.859972               0.0  ...           16.989369   
3             40.083853               1.0  ...           11.631093   
4             23.838820               2.0  ...           15.372885   
...                 ...               ...  ...                 ...   
4995          26.632876               0.0  ...           15.530375   
4996          13.090832               4.0  ...            9.113572   
4997          27.700626               3.0  ...           16.549603   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
0     157.398274  53.055261         0.0         NaN            1.0   
1     151.295654  60.628213         2.0         1.0            1.0   
2     183.900640  65.655529         0.0         1.0            0.0   
3     164.835570  38.357323         2.0         1.0            2.0   
4     166.303604  39.271753         NaN         0.0            1.0   
...          ...        ...         ...         ...            ...   
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0            NaN   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
0                 0.0            0.898032                  1.0      1.0  
1                 3.0            3.291397                  0.0      0.0  
2                 1.0            0.000000                  2.0      1.0  
3                 1.0            2.410233                  0.0      0.0  
4                 2.0            1.200275                  1.0      1.0  
...               ...                 ...                  ...      ...  
4995              1.0            6.146414           

In [139]:
# 6.3
#Drop columns with any null

df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[5000 rows x 0 columns]

from matplotlib import pyplot as plt
_df_5['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_7['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
# 6.4
#Drop columns with all null

df.dropna(axis=1, how='all')

In [144]:
# 8

df["net"] = df["hours_studied"] +  df["internet_access"]





**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).