**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np
myarr1= np.zeros(10)
print(myarr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Q1.2
import numpy as np
myarr2= np.array([5]*10)
print(myarr2)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Q1.3
import numpy as np
myarr3= np.arange(9).reshape(3,3)
print(myarr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Q1.4
import numpy as np
myarr4= np.random.rand()
print(myarr4)

0.24105399741308964


In [ ]:
#Q1.5
import numpy as np
myarr5= np.linspace(0,1,20)
print(myarr5)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#Q1.6
str= input("Enter:")
vowel="AEIOUaeiou"
count=0
for char in str:
  if char in vowel:
    count +=1
print("Number of vowels:",count)


Enter:hi, i am rashi
Number of vowels: 5


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [9]:
#Q2.1
import numpy as np
numbers = np.array([12,7,44,19,102,-8,33,56,77,90,-24,48])
arr= numbers[numbers%2==0]
print(arr)

[ 12  44 102  -8  56  90 -24  48]


In [10]:
#Q2.2
import numpy as np
arr=np.random.randint(10,101, size=(5,4))
print(arr)

[[ 38  70  33  86]
 [ 36  70  78  56]
 [ 74  77  90  11]
 [100  37  79  88]
 [ 13  86  40  80]]


In [11]:
#Q2.3
import numpy as py
arr=np.random.randint(10,101, size=(5,4))
subarray = arr[:3,:2]
print (subarray)

[[74 48]
 [60 14]
 [71 15]]


In [12]:
#Q2.4
import numpy as np
arr=np.random.randint(10,101, size=(5,4))
arr1= arr.flatten()
arr2=arr1.reshape(4,5)
print(arr2)

[[ 74  85  73  37  91]
 [ 44  59  61  84  57]
 [ 95  32  34  30  76]
 [100  39  53  88  53]]


In [8]:
#Q2.5
import numpy as np
arr=np.random.randint(10,101, size=(5,4))
arr1= arr.flatten()
print(arr1)

[66 25 98 20 85 77 58 36 25 57 34 95 36 90 91 52 58 45 55 76]


In [3]:
#Q2.6
import numpy as np
arr1=np.random.randint(10,101, size=(5,4))
arr2=np.random.randint(2,81, size=(4,3))
product=arr1 @ arr2
print(arr1)
print(arr2)
print("The product is:",product)

[[27 92 83 64]
 [25 96 22 12]
 [32 94 40 66]
 [33 70 66 71]
 [60 36 21 50]]
[[65 33 45]
 [ 7 62 56]
 [48 28 60]
 [41  3 60]]
The product is: [[ 9007  9111 15187]
 [ 3845  7429  8541]
 [ 7364  8202 13064]
 [ 8714  7490 13625]
 [ 7210  4950  8976]]


**Q.3**

(i) Check if matrix multiplication is valid

In [4]:
#your code here
rol1,col1 = arr1.shape
rol2,col2 = arr2.shape
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")


Multiplication is valid


(ii) Using loops (without using numpy)

In [5]:
#your code here
rol1 = 0
col2 = 0
for ele in arr1:
  rol1 += 1
for ele in arr2:
  col2 += 1
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


**Q.4**
(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [ ]:
x = [1,2,3,4,5]
y = [2,4,5,4,5]
mean_x= sum(x)/len(x)
mean_y=sum(y)/len(y)
print("The mean of x is",mean_x)
print("The mean of y is",mean_y)
numerator = 0
denominator = 0

for i in range(len(x)):
    numerator += (x[i] - mean_x) * (y[i] - mean_y)
    denominator += (x[i] - mean_x) ** 2

m = numerator / denominator
print("The slope is",m)

c=(mean_y)-(m*mean_x)
print("The intercept is",c)

The mean of x is 3.0
The mean of y is 4.0
The slope is 0.6
The intercept is 2.2


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).