**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
import numpy as np
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Q.1.2
import numpy as np
fives_array = np.full(10,5)
print(fives_array)


[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Q.1.3
import numpy as np
matrix_3x3 = np.arange(9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Q.1.4
import numpy as np
random_num = np.random.rand()
print(random_num)

0.14222074132162532


In [ ]:
#Q.1.5
import numpy as np
linear_points = np.linspace(0,1,20)
print(linear_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#Q.1.6
def count_vowels(s):
    count = 0
    vowels = "aeiouAEIOU"
    for char in s:
        if char in vowels:
            count += 1
    return count
sample_string = "it is amazing"
vowel_count = count_vowels(sample_string)
print(vowel_count)

5


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##Q.2.1
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
even_numbers = [num for num in
                numbers if num % 2 == 0]
print(even_numbers)

[12, 44, 102, -8, 56, 90, -24, 48]


In [ ]:
#Q.2.2
import numpy as np
array_2d = np.random.randint(10, 101, size=(5,4))
print(array_2d)


[[73 19 54 81]
 [93 81 61 50]
 [14 26 84 73]
 [47 72 94 74]
 [80 66 66 41]]


In [ ]:
#Q.2.3
subarray_3x2 = array_2d[:3, :2]
print(subarray_3x2)


[[73 19]
 [93 81]
 [14 26]]


In [ ]:
#Q.2.5 (assuming this was intended for Q.2.5, to flatten array_2d)
import numpy as np
array_1d = array_2d.flatten()
print(array_1d)

[73 19 54 81 93 81 61 50 14 26 84 73 47 72 94 74 80 66 66 41]


In [ ]:
#Q.2.6
import numpy as np
array1 = np.array([[1, 2],[3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = np.dot(array1, array2)
print(result)

**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
import numpy as np
def isValid(A,B):
  array1 = np.array(A)
  array2 = np.array(B)
  if array1.shape[1] == array2.shape[0]:
    print("Valid")
  else:
    print("Invalid Input")


(ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
  array1 = np.array(A)
  array2 = np.array(B)
  box = []
  for i in range(0,array1.shape[0]):
    for j in range(0,array2.shape[1]):
      y=0
      for k in range(0,array1.shape[1]):
        y += array1[i][k] * array2[k][j]
        box.append(y)

**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

# Initialize variables for sums
sum_X = 0
sum_y = 0

# Calculate sum of X
for val in X:
  sum_X += val
mean_X = sum_X / len(X)
print(f"Mean of X: {mean_X}")

# Calculate sum of y
for val in y:
  sum_y += val
mean_Y = sum_y / len(y)
print(f"Mean of Y: {mean_Y}")

n = len(X)
num = sum((X[i] - mean_X) * (y[i] - mean_Y) for i in range(n))
den = sum((X[i] - mean_X) ** 2 for i in range(n))
m = num / den
c = mean_Y - m * mean_X
print("Slope (m):", m)
print("Intercept (c):", c)
Y_pred = [m * x + c for x in X]
print("Predicted Y values:" , Y_pred)

Mean of X: 3.0
Mean of Y: 4.0
Slope (m): 0.6
Intercept (c): 2.2
Predicted Y values: [2.8000000000000003, 3.4000000000000004, 4.0, 4.6, 5.2]


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


In [2]:
import pandas as pd
import gdown

# Google Drive file ID for 'performance_dataset.csv'
file_id = '1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq'
url = f'https://drive.google.com/uc?id={file_id}'

# Define the local path where the file will be saved
file_path = 'performance_dataset.csv'

# Download the file using gdown
# If gdown is not installed, you might need to run: !pip install gdown
gdown.download(url, file_path, quiet=False)

df = pd.read_csv(file_path)
df_backup = df.copy()

print("--- DataFrame Head ---")
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\n--- DataFrame Info ---")
df.info()

print("\n--- DataFrame Describe (Numerical Columns) ---")
print(df.describe().to_markdown(numalign="left", stralign="left"))

print("\n--- DataFrame Shape ---")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Downloading...
From: https://drive.google.com/uc?id=1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq
To: /content/performance_dataset.csv
100%|██████████| 1.02M/1.02M [00:00<00:00, 106MB/s]

--- DataFrame Head ---
| hours_studied   | attendance_percent   | parent_education   | internet_access   | school_type   | sports_participation   | part_time_job   | siblings   | commute_time_mins   | favorite_subject   | club_member   | self_study_hours   | pet_count   | locker_number   | bus_route   | screen_time_weekly   | height_cm   | weight_kg   | lunch_type   | math_tutor   | reading_habit   | video_game_freq   | music_hours_weekly   | parent_meeting_freq   | uniform   |
|:----------------|:---------------------|:-------------------|:------------------|:--------------|:-----------------------|:----------------|:-----------|:--------------------|:-------------------|:--------------|:-------------------|:------------|:----------------|:------------|:---------------------|:------------|:------------|:-------------|:-------------|:----------------|:------------------|:---------------------|:----------------------|:----------|
| 4.74311         | 79.7815              | 3             

csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).