**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [67]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np
array1=np.zeros(10)
print(array1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [68]:
#Q.1.2
array2=np.full(10,5)
print(array2)

[5 5 5 5 5 5 5 5 5 5]


In [69]:
#Q1.3
array3=np.arange(9).reshape(3,3)
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
#Q1.4
np.random.random()



0.6689564175894912

In [71]:
#1.5
arr = np.linspace(0, 1, 20)
print(arr)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [72]:
#1.6
string=input('enter your string ')
vowels="AEIOUaeiou"
count=0
for i in range(len(string)):

  if string[i] in vowels:
   count+=1

print(count)

2


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [73]:
#2.1
numbers=[12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
even_numbers = [num for num in numbers if num % 2 == 0]

print(even_numbers)




[12, 44, 102, -8, 56, 90, -24, 48]


In [74]:
#2.2
arr_int = np.random.randint(10, 100, size=20).reshape(5,4)
print(arr_int)
#2.3
sub = arr_int[0:2,0:3]
print(sub)

[[97 27 48 77]
 [82 66 14 90]
 [65 94 22 49]
 [35 43 60 34]
 [72 74 43 87]]
[[97 27 48]
 [82 66 14]]


In [75]:
#2.4
arr1= np.array([1,3,4,4,33,3,33,33,3,333,3,33,3332,54,765,443,9609,567,3,5])
print(arr1.reshape(4,5))


[[   1    3    4    4   33]
 [   3   33   33    3  333]
 [   3   33 3332   54  765]
 [ 443 9609  567    3    5]]


In [76]:
#2.5
arr2=np.array([[1 ,3,4,4,33]
 ,[3,33 ,  33  ,  3 , 333]
 ,[   3  , 33, 3332  , 54 , 765]
 ,[ 443, 9609 , 567  , 3   , 5]])
print(arr2.flatten())

[   1    3    4    4   33    3   33   33    3  333    3   33 3332   54
  765  443 9609  567    3    5]


In [77]:
#2.6
mat1=np.array([[1,3,6,8],
              [1,5,9,2],
              [3,4,7,12]])
mat2=np.random.randint(12,400,size=16).reshape(4,4)
np.dot(mat1,mat2)


array([[5826, 4704, 3674, 2812],
       [4860, 3247, 3937, 2367],
       [8138, 6994, 5259, 4422]])

**Q.3**

(i) Check if matrix multiplication is valid

In [78]:
#3.1
mat1=np.random.randint(1,10,size=20).reshape(4,5)
mat2=np.random.randint(3,40,size=15).reshape(5,3)
if mat1.shape[1]==mat2.shape[0]: print("matrix multiplication is valid")
else: print("matrix multiplication is invalid")



matrix multiplication is valid


(ii) Using loops (without using numpy)

In [79]:
#your code here
mat1=np.random.randint(1,10,size=20).reshape(4,5)
mat2=np.random.randint(3,40,size=12).reshape(4,3)
if len(mat1[1])==len(mat2): print("matrix multiplication is valid")
else: print("matrix multiplication is invalid")

matrix multiplication is invalid


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [80]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]
sumX=0
sumY=0
for i in range(len(X)):
    sumX+=X[i]
    meanX=sumX/(len(X))
print("mean of X is",meanX)
for J in range(len(Y)):
    sumY+=Y[J]
    meanY=sumY/(len(Y))
print("mean of Y is",meanY)
numerator=0
denominator=0
for i in range(len(X)):
    numerator+=(X[i]-meanX)*(Y[i]-meanY)
    denominator+=(X[i]-meanX)**2
m=numerator/denominator
print("slope is ",m)
c=meanY-(m*meanX)
print("interceptis ",c)
predicted_values=[(nums*m)+c for nums in X]
print(predicted_values)






mean of X is 3.0
mean of Y is 4.0
slope is  0.6
interceptis  2.2
[2.8000000000000003, 3.4000000000000004, 4.0, 4.6, 5.2]


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [81]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [82]:
import pandas as pd

#1
dataset_url = "https://drive.google.com/uc?id=1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq&export=download"
dataset = pd.read_csv(dataset_url)
df_backup=dataset.copy()


In [83]:
#2
dataset.shape


(5000, 25)

In [84]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   hours_studied         4750 non-null   float64
 1   attendance_percent    4750 non-null   float64
 2   parent_education      4750 non-null   float64
 3   internet_access       4750 non-null   float64
 4   school_type           4750 non-null   float64
 5   sports_participation  4750 non-null   float64
 6   part_time_job         4750 non-null   float64
 7   siblings              4750 non-null   float64
 8   commute_time_mins     4750 non-null   float64
 9   favorite_subject      4750 non-null   float64
 10  club_member           4750 non-null   float64
 11  self_study_hours      4750 non-null   float64
 12  pet_count             4750 non-null   float64
 13  locker_number         4750 non-null   float64
 14  bus_route             4750 non-null   float64
 15  screen_time_weekly   

In [85]:
dataset.head()

hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [86]:
dataset.describe()

hours_studied  attendance_percent  parent_education  internet_access  \
count    4750.000000         4750.000000       4750.000000      4750.000000   
mean        8.078365           74.696663          1.511579         0.503158   
std         2.948970           14.296907          1.124102         0.500043   
min         0.000000           40.000000          0.000000         0.000000   
25%         6.067024           64.666932          0.000000         0.000000   
50%         8.113447           74.893237          2.000000         1.000000   
75%        10.068370           85.104610          3.000000         1.000000   
max        18.714738          100.000000          3.000000         1.000000   

       school_type  sports_participation  part_time_job     siblings  \
count  4750.000000           4750.000000    4750.000000  4750.000000   
mean      0.993263              1.504421       0.489053     2.032000   
std       0.813627              1.111343       0.499933     1.426602   
min       0.000000              0.000000       0.000000     0.000000   
25%       0.000000              1.000000       0.000000     1.000000   
50%       1.000000              2.000000       0.000000     2.000000   
75%       2.000000              2.000000       1.000000     3.000000   
max       2.000000              3.000000       1.000000     9.000000   

       commute_time_mins  favorite_subject  ...  screen_time_weekly  \
count        4750.000000       4750.000000  ...         4750.000000   
mean           30.460856          2.004421  ...           13.902894   
std            14.357631          1.414877  ...            5.998482   
min             5.000000          0.000000  ...            0.000000   
25%            20.185850          1.000000  ...            9.899414   
50%            29.999436          2.000000  ...           13.893609   
75%            40.205028          3.000000  ...           18.027138   
max            85.268616          4.000000  ...           34.499493   

         height_cm    weight_kg   lunch_type   math_tutor  reading_habit  \
count  4750.000000  4750.000000  4750.000000  4750.000000    4750.000000   
mean    160.070126    54.852794     0.987789     0.507158       1.507789   
std      11.884900    11.902029     0.820008     0.500001       1.109428   
min     130.000000    30.000000     0.000000     0.000000       0.000000   
25%     151.927614    46.584774     0.000000     0.000000       1.000000   
50%     159.997054    54.795697     1.000000     1.000000       1.000000   
75%     168.187011    63.084992     2.000000     1.000000       3.000000   
max     200.000000    96.824370     2.000000     1.000000       3.000000   

       video_game_freq  music_hours_weekly  parent_meeting_freq      uniform  
count      4750.000000         4750.000000          4750.000000  4750.000000  
mean          1.497474            5.047120             0.999579     0.504632  
std           1.109452            2.861449             0.813913     0.500031  
min           0.000000            0.000000             0.000000     0.000000  
25%           1.000000            2.997055             0.000000     0.000000  
50%           2.000000            5.031735             1.000000     1.000000  
75%           2.000000            7.043462             2.000000     1.000000  
max           3.000000           13.983962             2.000000     1.000000  

[8 rows x 25 columns]

In [87]:
dataset.tail()

hours_studied  attendance_percent  parent_education  internet_access  \
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
4995          26.632876               0.0  ...           15.530375   
4996          13.090832               4.0  ...            9.113572   
4997          27.700626               3.0  ...           16.549603   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0            NaN   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
4995              1.0            6.146414                  2.0      0.0  
4996              2.0            6.044880                  2.0      1.0  
4997              1.0            7.852906                  NaN      1.0  
4998              2.0            9.503284                  2.0      1.0  
4999              1.0            6.292816                  1.0      1.0  

[5 rows x 25 columns]

In [88]:
dataset.attendance_percent

0       79.781453
1       97.666558
2       57.950598
3       84.636899
4       58.081774
          ...    
4995    66.031236
4996    54.031024
4997    67.916004
4998    83.729465
4999    89.559193
Name: attendance_percent, Length: 5000, dtype: float64

In [89]:
dataset['attendance_percent']

0       79.781453
1       97.666558
2       57.950598
3       84.636899
4       58.081774
          ...    
4995    66.031236
4996    54.031024
4997    67.916004
4998    83.729465
4999    89.559193
Name: attendance_percent, Length: 5000, dtype: float64

In [90]:
dataset.rename(columns={'commute_time_mins':'commute time_minutes'})

hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
0             NaN                   1.0            0.0       4.0   
1             0.0                   3.0            NaN       1.0   
2             0.0                   1.0            0.0       3.0   
3             0.0                   2.0            0.0       4.0   
4             0.0                   3.0            1.0       2.0   
...           ...                   ...            ...       ...   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute time_minutes  favorite_subject  ...  screen_time_weekly  \
0                31.681382               2.0  ...            2.339672   
1                19.423883               4.0  ...                 NaN   
2                28.859972               0.0  ...           16.989369   
3                40.083853               1.0  ...           11.631093   
4                23.838820               2.0  ...           15.372885   
...                    ...               ...  ...                 ...   
4995             26.632876               0.0  ...           15.530375   
4996             13.090832               4.0  ...            9.113572   
4997             27.700626               3.0  ...           16.549603   
4998             31.984014               0.0  ...           15.199985   
4999              7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
0     157.398274  53.055261         0.0         NaN            1.0   
1     151.295654  60.628213         2.0         1.0            1.0   
2     183.900640  65.655529         0.0         1.0            0.0   
3     164.835570  38.357323         2.0         1.0            2.0   
4     166.303604  39.271753         NaN         0.0            1.0   
...          ...        ...         ...         ...            ...   
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0            NaN   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
0                 0.0            0.898032                  1.0      1.0  
1                 3.0            3.291397                  0.0      0.0  
2                 1.0            0.000000                  2.0      1.0  
3                 1.0            2.410233                  0.0      0.0  
4                 2.0            1.200275                  1.0      1.0  
...               ...                 ...                  ...      ...  
4995            

In [91]:
dataset['music_hours_weekly']+1
dataset['music_hours_weekly'].max


<bound method Series.max of 0       0.898032
1       3.291397
2       0.000000
3       2.410233
4       1.200275
          ...   
4995    6.146414
4996    6.044880
4997    7.852906
4998    9.503284
4999    6.292816
Name: music_hours_weekly, Length: 5000, dtype: float64>

In [92]:
dataset['music_hours_weekly'].astype(str)

0       0.8980323269413635
1        3.291396790154886
2                      0.0
3        2.410232988384984
4       1.2002750483654423
               ...        
4995      6.14641376527265
4996     6.044879689707139
4997     7.852906215248068
4998     9.503284168975233
4999     6.292815983158207
Name: music_hours_weekly, Length: 5000, dtype: object

In [93]:
dataset['school_type'].replace({np.nan: None})

0       None
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
4995     2.0
4996    None
4997     1.0
4998     0.0
4999     0.0
Name: school_type, Length: 5000, dtype: object

In [94]:
dataset.iloc[:,5]

0       1.0
1       3.0
2       1.0
3       2.0
4       3.0
       ... 
4995    3.0
4996    NaN
4997    0.0
4998    NaN
4999    1.0
Name: sports_participation, Length: 5000, dtype: float64

In [95]:
dataset.iloc[[1,9,10],3]

1     1.0
9     0.0
10    1.0
Name: internet_access, dtype: float64

In [96]:
dataset.iloc[0]

hours_studied             4.743108
attendance_percent       79.781453
parent_education          3.000000
internet_access                NaN
school_type                    NaN
sports_participation      1.000000
part_time_job             0.000000
siblings                  4.000000
commute_time_mins        31.681382
favorite_subject          2.000000
club_member               0.000000
self_study_hours          1.230251
pet_count                 0.000000
locker_number           169.000000
bus_route                 2.000000
screen_time_weekly        2.339672
height_cm               157.398274
weight_kg                53.055261
lunch_type                0.000000
math_tutor                     NaN
reading_habit             1.000000
video_game_freq           0.000000
music_hours_weekly        0.898032
parent_meeting_freq       1.000000
uniform                   1.000000
Name: 0, dtype: float64

In [97]:
dataset.iloc[-5:]

hours_studied  attendance_percent  parent_education  internet_access  \
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
4995          26.632876               0.0  ...           15.530375   
4996          13.090832               4.0  ...            9.113572   
4997          27.700626               3.0  ...           16.549603   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0            NaN   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
4995              1.0            6.146414                  2.0      0.0  
4996              2.0            6.044880                  2.0      1.0  
4997              1.0            7.852906                  NaN      1.0  
4998              2.0            9.503284                  2.0      1.0  
4999              1.0            6.292816                  1.0      1.0  

[5 rows x 25 columns]

In [98]:
dataset.isnull()
dataset.isnull().sum()

hours_studied           250
attendance_percent      250
parent_education        250
internet_access         250
school_type             250
sports_participation    250
part_time_job           250
siblings                250
commute_time_mins       250
favorite_subject        250
club_member             250
self_study_hours        250
pet_count               250
locker_number           250
bus_route               250
screen_time_weekly      250
height_cm               250
weight_kg               250
lunch_type              250
math_tutor              250
reading_habit           250
video_game_freq         250
music_hours_weekly      250
parent_meeting_freq     250
uniform                 250
dtype: int64

In [99]:
dataset['internet_access'].isnull()

0        True
1       False
2       False
3       False
4       False
        ...  
4995    False
4996    False
4997    False
4998     True
4999    False
Name: internet_access, Length: 5000, dtype: bool

In [100]:
#dataset.dropna()

In [101]:
#dataset.dropna(axis=1)

In [102]:
#dataset.fillna(0)

In [103]:
dataset.fillna({'reading_habit':'not a reader','math_tutor':'self study'})

hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
0             NaN                   1.0            0.0       4.0   
1             0.0                   3.0            NaN       1.0   
2             0.0                   1.0            0.0       3.0   
3             0.0                   2.0            0.0       4.0   
4             0.0                   3.0            1.0       2.0   
...           ...                   ...            ...       ...   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
0             31.681382               2.0  ...            2.339672   
1             19.423883               4.0  ...                 NaN   
2             28.859972               0.0  ...           16.989369   
3             40.083853               1.0  ...           11.631093   
4             23.838820               2.0  ...           15.372885   
...                 ...               ...  ...                 ...   
4995          26.632876               0.0  ...           15.530375   
4996          13.090832               4.0  ...            9.113572   
4997          27.700626               3.0  ...           16.549603   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
0     157.398274  53.055261         0.0  self study            1.0   
1     151.295654  60.628213         2.0         1.0            1.0   
2     183.900640  65.655529         0.0         1.0            0.0   
3     164.835570  38.357323         2.0         1.0            2.0   
4     166.303604  39.271753         NaN         0.0            1.0   
...          ...        ...         ...         ...            ...   
4995  160.210764  60.125200         2.0         0.0            2.0   
4996  158.662350  52.236613         0.0         0.0   not a reader   
4997  147.579151  48.295257         1.0         1.0            3.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0  self study            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq uniform  
0                 0.0            0.898032                  1.0     1.0  
1                 3.0            3.291397                  0.0     0.0  
2                 1.0            0.000000                  2.0     1.0  
3                 1.0            2.410233                  0.0     0.0  
4                 2.0            1.200275                  1.0     1.0  
...               ...                 ...                  ...     ...  
4995              1.0            6.146414                  

In [104]:
dataset.drop('internet_access',axis=1)

hours_studied  attendance_percent  parent_education  school_type  \
0          4.743108           79.781453               3.0          NaN   
1         10.992036           97.666558               3.0          0.0   
2          8.848935           57.950598               2.0          0.0   
3          3.481116           84.636899               0.0          0.0   
4          6.264199           58.081774               1.0          0.0   
...             ...                 ...               ...          ...   
4995       4.633189           66.031236               0.0          2.0   
4996       3.744086           54.031024               2.0          NaN   
4997       2.420855           67.916004               3.0          1.0   
4998      10.741467           83.729465               2.0          0.0   
4999       3.938481           89.559193               2.0          0.0   

      sports_participation  part_time_job  siblings  commute_time_mins  \
0                      1.0            0.0       4.0          31.681382   
1                      3.0            NaN       1.0          19.423883   
2                      1.0            0.0       3.0          28.859972   
3                      2.0            0.0       4.0          40.083853   
4                      3.0            1.0       2.0          23.838820   
...                    ...            ...       ...                ...   
4995                   3.0            1.0       3.0          26.632876   
4996                   NaN            1.0       0.0          13.090832   
4997                   0.0            0.0       2.0          27.700626   
4998                   NaN            1.0       1.0          31.984014   
4999                   1.0            1.0       4.0           7.913338   

      favorite_subject  club_member  ...  screen_time_weekly   height_cm  \
0                  2.0          0.0  ...            2.339672  157.398274   
1                  4.0          NaN  ...                 NaN  151.295654   
2                  0.0          1.0  ...           16.989369  183.900640   
3                  1.0          1.0  ...           11.631093  164.835570   
4                  2.0          1.0  ...           15.372885  166.303604   
...                ...          ...  ...                 ...         ...   
4995               0.0          0.0  ...           15.530375  160.210764   
4996               4.0          1.0  ...            9.113572  158.662350   
4997               3.0          1.0  ...           16.549603  147.579151   
4998               0.0          0.0  ...           15.199985  144.516353   
4999               0.0          0.0  ...           14.383070  165.746985   

      weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0     53.055261         0.0         NaN            1.0              0.0   
1     60.628213         2.0         1.0            1.0              3.0   
2     65.655529         0.0         1.0            0.0              1.0   
3     38.357323         2.0         1.0            2.0              1.0   
4     39.271753         NaN         0.0            1.0              2.0   
...         ...         ...         ...            ...              ...   
4995  60.125200         2.0         0.0            2.0              1.0   
4996  52.236613         0.0         0.0            NaN              2.0   
4997  48.295257         1.0         1.0            3.0              1.0   
4998  67.014608         1.0         1.0            0.0              2.0   
4999  48.699774         2.0         NaN            0.0              1.0   

      music_hours_weekly  parent_meeting_freq  uniform  
0               0.898032                  1.0      1.0  
1               3.291397                  0.0      0.0  
2               0.000000                  2.0      1.0  
3               2.410233                  0.0      0.0  
4               1.200275                  1.0      1.0  
...                  ...                  ...      ...  
4995           

In [105]:
dataset.loc[(dataset.attendance_percent>=75) & (dataset.sports_participation!=0)]

hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
3          3.481116           84.636899               0.0              0.0   
8         11.797809           84.437431               3.0              1.0   
9          5.399779           76.552077               2.0              0.0   
...             ...                 ...               ...              ...   
4992       2.269449           91.068824               0.0              1.0   
4993      10.335344          100.000000               3.0              0.0   
4994       4.826182           84.737572               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
0             NaN                   1.0            0.0       4.0   
1             0.0                   3.0            NaN       1.0   
3             0.0                   2.0            0.0       4.0   
8             0.0                   1.0            0.0       0.0   
9             1.0                   2.0            0.0       4.0   
...           ...                   ...            ...       ...   
4992          2.0                   1.0            0.0       0.0   
4993          1.0                   3.0            0.0       2.0   
4994          2.0                   1.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...  screen_time_weekly  \
0             31.681382               2.0  ...            2.339672   
1             19.423883               4.0  ...                 NaN   
3             40.083853               1.0  ...           11.631093   
8             15.620543               1.0  ...            8.101199   
9             22.012151               4.0  ...           20.415948   
...                 ...               ...  ...                 ...   
4992          36.444477               3.0  ...           16.915729   
4993          58.279255               4.0  ...           21.269810   
4994          11.971699               1.0  ...           11.709831   
4998          31.984014               0.0  ...           15.199985   
4999           7.913338               0.0  ...           14.383070   

       height_cm  weight_kg  lunch_type  math_tutor  reading_habit  \
0     157.398274  53.055261         0.0         NaN            1.0   
1     151.295654  60.628213         2.0         1.0            1.0   
3     164.835570  38.357323         2.0         1.0            2.0   
8     155.137833  46.922817         0.0         1.0            1.0   
9     161.578542  61.015816         1.0         0.0            0.0   
...          ...        ...         ...         ...            ...   
4992  155.987731  71.157416         2.0         1.0            1.0   
4993  165.948164  40.170458         2.0         1.0            0.0   
4994  167.442375  33.571682         1.0         1.0            0.0   
4998  144.516353  67.014608         1.0         1.0            0.0   
4999  165.746985  48.699774         2.0         NaN            0.0   

      video_game_freq  music_hours_weekly  parent_meeting_freq  uniform  
0                 0.0            0.898032                  1.0      1.0  
1                 3.0            3.291397                  0.0      0.0  
3                 1.0            2.410233                  0.0      0.0  
8                 1.0            5.892455                  2.0      1.0  
9                 NaN            0.000000                  0.0      0.0  
...               ...                 ...                  ...      ...  
4992              1.0            9.635729           

In [106]:
dataset["productive_time"]=dataset.hours_studied +dataset.reading_habit
dataset.productive_time

0        5.743108
1       11.992036
2        8.848935
3        5.481116
4        7.264199
          ...    
4995     6.633189
4996          NaN
4997     5.420855
4998    10.741467
4999     3.938481
Name: productive_time, Length: 5000, dtype: float64