**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np

arr=np.full(10,0)
print(arr)


[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Q.1.2
arr_fives = np.full(10, 5)
print(arr_fives)


[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#1.3
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#1.4
rand_num = np.random.rand()
print(rand_num)


0.13213063147649506


In [ ]:
#1.5
lin_space = np.linspace(0, 1, 20)
print(lin_space)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#1.6
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

user_string = input("Enter a string: ")

print("Number of vowels:", count_vowels(user_string))


Enter a string: hello my friend 
Number of vowels: 4


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
#2.1
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

even_numbers = numbers[0::1]
even_numbers = [x for x in even_numbers if x % 2 == 0]

print("Even numbers:", even_numbers)


Even numbers: [12, 44, 102, -8, 56, 90, -24, 48]


In [ ]:
#2.2
import numpy as np

arr = np.random.randint(10, 101, size=(5, 4))
print("5x4 array:\n", arr)


5x4 array:
 [[ 66  14  51  58]
 [ 96 100  81  71]
 [ 82  87  28  75]
 [ 63  84  98  13]
 [ 98  99  89  37]]


In [ ]:
#2.3
subarray = arr[:3, :2]
print("3x2 subarray:\n", subarray)


3x2 subarray:
 [[ 66  14]
 [ 96 100]
 [ 82  87]]


In [ ]:
#2.4
numbers_fixed = numbers[:15]
reshaped = numbers_fixed.reshape(3, 5)
print(reshaped)


[[ 12   7  44  19 102]
 [ -8  33  56  77  90]
 [121 -24  48   0   0]]


In [ ]:
#2.5
flattened = reshaped.flatten()
print("Flattened array:", flattened)


Flattened array: [ 12   7  44  19 102  -8  33  56  77  90 121 -24  48   0   0]


In [ ]:
#2.6
A = arr
B = np.random.randint(1, 10, (4, 3))

result = np.matmul(A, B)
print("Matrix multiplication result:\n", result)


Matrix multiplication result:
 [[1033  864  910]
 [2240 1509 1829]
 [1736 1231 1339]
 [1826 1008 1546]
 [2255 1305 1851]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
("""Interactive NumPy matrix multiplication validator.

This script reads two matrices A and B from the terminal and reports
whether the matrix product A x B is defined (i.e. number of columns
in A equals number of rows in B).

Requirements: Python 3.8+ and NumPy installed. If NumPy is missing the
script prints an instruction to install it.

Usage (PowerShell):
	python "matrixmultiplication.py"

Example input flow:
	Enter rows for matrix A: 2
	Enter columns for matrix A: 3
	Row 1 (3 values): 1 2 3
	Row 2 (3 values): 4 5 6

The script accepts integers or floats for values.
""")

from typing import List
import sys

try:
	import numpy as np
except Exception:
	np = None


def read_int(prompt: str) -> int:
	while True:
		try:
			s = input(prompt).strip()
			return int(s)
		except ValueError:
			print("Please enter a valid integer.")


def read_matrix(name: str) -> List[List[float]]:
	rows = read_int(f"Enter number of rows for matrix {name}: ")
	cols = read_int(f"Enter number of columns for matrix {name}: ")
	if rows <= 0 or cols <= 0:
		print("Rows and columns must be positive.")
		return read_matrix(name)
	mat = []
	for r in range(rows):
		while True:
			s = input(f"Row {r+1} ({cols} values): ").strip()
			parts = s.split()
			if len(parts) != cols:
				print(f"Expected {cols} values, got {len(parts)}. Try again.")
				continue
			row = []
			for p in parts:
				try:
					if "." in p or "e" in p.lower():
						val = float(p)
					else:
						val = int(p)
				except ValueError:
					try:
						val = float(p)
					except ValueError:
						print(f"Could not parse '{p}' as a number. Try the row again.")
						break
				row.append(val)
			else:
				mat.append(row)
				break
	return mat


def can_multiply_numpy(A, B) -> bool:
	if np is None:
		raise RuntimeError("NumPy is not installed. Install with: pip install numpy")
	a = np.array(A)
	b = np.array(B)
	if a.ndim != 2 or b.ndim != 2:
		return False
	return a.shape[1] == b.shape[0]


def main():
	print("NumPy matrix multiplication validator")
	if np is None:
		print("Warning: NumPy is not installed. Install with: pip install numpy")
	A = read_matrix('A')
	B = read_matrix('B')

	# basic shape validation
	cols_A = len(A[0])
	rows_B = len(B)
	defined = False
	try:
		if np is not None:
			defined = can_multiply_numpy(A, B)
		else:
			defined = (cols_A == rows_B)
	except Exception as e:
		# fallback to simple check
		print("NumPy check failed, falling back to basic check:", e)
		defined = (cols_A == rows_B)

	print(f"Matrix A is {len(A)}x{len(A[0])}")
	print(f"Matrix B is {len(B)}x{len(B[0])}")
	if defined:
		print("Result: A x B is defined (multiplication allowed).")
	else:
		print("Result: A x B is NOT defined (columns of A != rows of B).")


if __name__ == '__main__':
	try:
		main()
	except KeyboardInterrupt:
		print("\nInterrupted.")
		sys.exit(1)



NumPy matrix multiplication validator
Enter number of rows for matrix A: 3
Enter number of columns for matrix A: 2
Row 1 (2 values): 5,4
Expected 2 values, got 1. Try again.
Row 1 (2 values): 4 6
Row 2 (2 values): 6 7
Row 3 (2 values): 9 8
Enter number of rows for matrix B: 2
Enter number of columns for matrix B: 1
Row 1 (1 values): 4
Row 2 (1 values): 3
Matrix A is 3x2
Matrix B is 2x1
Result: A x B is defined (multiplication allowed).


(ii) Using loops (without using numpy)

In [ ]:
"""Pure Python matrix multiplication validator (no NumPy required).

This script reads two matrices A and B from the terminal and reports
whether the matrix product A x B is defined (i.e. number of columns
in A equals number of rows in B).

No external dependencies—uses only Python standard library.

Usage (PowerShell):
    python "matrixmultiplication_pure.py"

Example input flow:
    Enter number of rows for matrix A: 2
    Enter number of columns for matrix A: 3
    Row 1 (3 values): 1 2 3
    Row 2 (3 values): 4 5 6
    Enter number of rows for matrix B: 3
    Enter number of columns for matrix B: 2
    Row 1 (2 values): 7 8
    Row 2 (2 values): 9 10
    Row 3 (2 values): 11 12

The script accepts integers or floats for values.
"""

from typing import List
import sys


def read_int(prompt: str) -> int:
    """Read and validate an integer from user input."""
    while True:
        try:
            s = input(prompt).strip()
            return int(s)
        except ValueError:
            print("Please enter a valid integer.")


def read_matrix(name: str) -> List[List]:
    """Read a matrix from user input.

    Returns a list of rows, where each row is a list of numbers (int or float).
    """
    rows = read_int(f"Enter number of rows for matrix {name}: ")
    cols = read_int(f"Enter number of columns for matrix {name}: ")

    if rows <= 0 or cols <= 0:
        print("Rows and columns must be positive integers.")
        return read_matrix(name)

    matrix = []
    for r in range(rows):
        while True:
            s = input(f"Row {r+1} ({cols} values): ").strip()
            parts = s.split()

            if len(parts) != cols:
                print(f"Expected {cols} values, got {len(parts)}. Try again.")
                continue

            row = []
            valid = True
            for p in parts:
                try:
                    # Try int first
                    if "." not in p and "e" not in p.lower():
                        val = int(p)
                    else:
                        val = float(p)
                except ValueError:
                    print(f"Could not parse '{p}' as a number. Try the row again.")
                    valid = False
                    break
                row.append(val)

            if valid:
                matrix.append(row)
                break

    return matrix


def validate_matrix(matrix: List[List]) -> bool:
    """Check if matrix is valid (non-empty and all rows have same length)."""
    if not matrix or len(matrix) == 0:
        return False
    if not all(isinstance(row, list) for row in matrix):
        return False

    first_row_len = len(matrix[0])
    if first_row_len == 0:
        return False

    return all(len(row) == first_row_len for row in matrix)


def can_multiply(A: List[List], B: List[List]) -> bool:
    """Check if matrix multiplication A x B is defined.

    Returns True if:
    - Both A and B are valid matrices
    - number of columns in A == number of rows in B
    """
    if not validate_matrix(A) or not validate_matrix(B):
        return False

    cols_A = len(A[0])
    rows_B = len(B)
    return cols_A == rows_B


def display_matrix(matrix: List[List], name: str):
    """Pretty-print a matrix."""
    print(f"\nMatrix {name}:")
    for row in matrix:
        print("  [", " ".join(f"{val:8.2f}" if isinstance(val, float) else f"{val:8}" for val in row), "]")


def main():
    print("=" * 60)
    print("Pure Python Matrix Multiplication Validator")
    print("=" * 60)
    print()

    A = read_matrix('A')
    print()
    B = read_matrix('B')
    print()

    # Validate and check
    if not validate_matrix(A):
        print("Error: Matrix A is invalid.")
        return
    if not validate_matrix(B):
        print("Error: Matrix B is invalid.")
        return

    display_matrix(A, "A")
    display_matrix(B, "B")
    print()

    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    print(f"Matrix A dimensions: {rows_A} x {cols_A}")
    print(f"Matrix B dimensions: {rows_B} x {cols_B}")
    print()

    is_valid = can_multiply(A, B)

    if is_valid:
        print("✓ Result: A x B IS DEFINED")
        print(f"  Multiplication is valid because:")
        print(f"  - Number of columns in A ({cols_A}) == Number of rows in B ({rows_B})")
        print(f"  - The product will be a {rows_A} x {cols_B} matrix")
    else:
        print("✗ Result: A x B IS NOT DEFINED")
        print(f"  Multiplication is invalid because:")
        print(f"  - Number of columns in A ({cols_A}) != Number of rows in B ({rows_B})")

    print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


Pure Python Matrix Multiplication Validator

Enter number of rows for matrix A: 1
Enter number of columns for matrix A: 2
Row 1 (2 values): 2
Expected 2 values, got 1. Try again.
Row 1 (2 values): 3 2

Enter number of rows for matrix B: 2
Enter number of columns for matrix B: 3
Row 1 (3 values): 5 4 6
Row 2 (3 values): 3 4 2


Matrix A:
  [        3        2 ]

Matrix B:
  [        5        4        6 ]
  [        3        4        2 ]

Matrix A dimensions: 1 x 2
Matrix B dimensions: 2 x 3

✓ Result: A x B IS DEFINED
  Multiplication is valid because:
  - Number of columns in A (2) == Number of rows in B (2)
  - The product will be a 1 x 3 matrix



**Q.4**
(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [ ]:
"""Pure Python Linear Regression Calculator (no libraries).

Computes mean, slope, intercept, and predicted values for simple linear regression.
Formula: y = mx + c
where m = slope, c = intercept
"""


def mean(data):
    """Calculate the mean of a list of numbers."""
    return sum(data) / len(data)


def calculate_slope_and_intercept(X, y):
    """Calculate slope (m) and intercept (c) for linear regression.

    Using the formulas:
    m = Σ((x - mean_x) * (y - mean_y)) / Σ((x - mean_x)²)
    c = mean_y - m * mean_x
    """
    n = len(X)
    mean_x = mean(X)
    mean_y = mean(y)

    # Calculate numerator and denominator for slope
    numerator = sum((X[i] - mean_x) * (y[i] - mean_y) for i in range(n))
    denominator = sum((X[i] - mean_x) ** 2 for i in range(n))

    # Avoid division by zero
    if denominator == 0:
        raise ValueError("Cannot calculate slope: denominator is zero")

    m = numerator / denominator
    c = mean_y - m * mean_x

    return m, c


def predict(X, m, c):
    """Predict y values using the linear equation y = mx + c."""
    return [m * x + c for x in X]


def print_results(X, y, mean_x, mean_y, m, c, y_pred):
    """Pretty-print all results."""
    print("=" * 70)
    print("LINEAR REGRESSION ANALYSIS (Pure Python, No Libraries)")
    print("=" * 70)
    print()

    print("INPUT DATA:")
    print(f"  X values: {X}")
    print(f"  y values: {y}")
    print()

    print("CALCULATED VALUES:")
    print(f"  Mean of X:  {mean_x:.4f}")
    print(f"  Mean of y:  {mean_y:.4f}")
    print()

    print("LINEAR REGRESSION (y = mx + c):")
    print(f"  Slope (m):      {m:.4f}")
    print(f"  Intercept (c):  {c:.4f}")
    print()

    print("PREDICTED VALUES:")
    print(f"  {'X':>5} | {'Actual y':>10} | {'Predicted y':>12} | {'Error':>8}")
    print("  " + "-" * 50)
    for i in range(len(X)):
        error = y[i] - y_pred[i]
        print(f"  {X[i]:>5} | {y[i]:>10} | {y_pred[i]:>12.4f} | {error:>8.4f}")

    print()
    print("EQUATION: y = {:.4f}x + {:.4f}".format(m, c))
    print("=" * 70)


def main():
    # Given data
    X = [1, 2, 3, 4, 5]
    y = [2, 4, 5, 4, 5]

    # Compute mean of X and y
    mean_x = mean(X)
    mean_y = mean(y)

    # Compute slope and intercept
    m, c = calculate_slope_and_intercept(X, y)

    # Compute predicted values
    y_pred = predict(X, m, c)

    # Display results
    print_results(X, y, mean_x, mean_y, m, c, y_pred)

    # Return results for verification
    return {
        'mean_X': mean_x,
        'mean_y': mean_y,
        'slope': m,
        'intercept': c,
        'predicted': y_pred
    }


if __name__ == '__main__':
    results = main()

    # Summary
    print("\nQUICK REFERENCE:")
    print(f"  Mean of X:     {results['mean_X']:.4f}")
    print(f"  Mean of y:     {results['mean_y']:.4f}")
    print(f"  Slope (m):     {results['slope']:.4f}")
    print(f"  Intercept (c): {results['intercept']:.4f}")
    print(f"  Predicted y:   {[round(p, 4) for p in results['predicted']]}")


LINEAR REGRESSION ANALYSIS (Pure Python, No Libraries)

INPUT DATA:
  X values: [1, 2, 3, 4, 5]
  y values: [2, 4, 5, 4, 5]

CALCULATED VALUES:
  Mean of X:  3.0000
  Mean of y:  4.0000

LINEAR REGRESSION (y = mx + c):
  Slope (m):      0.6000
  Intercept (c):  2.2000

PREDICTED VALUES:
      X |   Actual y |  Predicted y |    Error
  --------------------------------------------------
      1 |          2 |       2.8000 |  -0.8000
      2 |          4 |       3.4000 |   0.6000
      3 |          5 |       4.0000 |   1.0000
      4 |          4 |       4.6000 |  -0.6000
      5 |          5 |       5.2000 |  -0.2000

EQUATION: y = 0.6000x + 2.2000

QUICK REFERENCE:
  Mean of X:     3.0000
  Mean of y:     4.0000
  Slope (m):     0.6000
  Intercept (c): 2.2000
  Predicted y:   [2.8, 3.4, 4.0, 4.6, 5.2]


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [9]:
from google.colab import files
uploaded = files.upload()


Saving performance_dataset.csv to performance_dataset.csv


In [10]:
#1
import pandas as pd

df = pd.read_csv('performance_dataset.csv')
backup_df = df.copy()

df.head()




hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...                 NaN  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         NaN            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         NaN         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [11]:
#2
df.info()
df.head()
df.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   hours_studied         4750 non-null   float64
 1   attendance_percent    4750 non-null   float64
 2   parent_education      4750 non-null   float64
 3   internet_access       4750 non-null   float64
 4   school_type           4750 non-null   float64
 5   sports_participation  4750 non-null   float64
 6   part_time_job         4750 non-null   float64
 7   siblings              4750 non-null   float64
 8   commute_time_mins     4750 non-null   float64
 9   favorite_subject      4750 non-null   float64
 10  club_member           4750 non-null   float64
 11  self_study_hours      4750 non-null   float64
 12  pet_count             4750 non-null   float64
 13  locker_number         4750 non-null   float64
 14  bus_route             4750 non-null   float64
 15  screen_time_weekly   

hours_studied  attendance_percent  parent_education  internet_access  \
count    4750.000000         4750.000000       4750.000000      4750.000000   
mean        8.078365           74.696663          1.511579         0.503158   
std         2.948970           14.296907          1.124102         0.500043   
min         0.000000           40.000000          0.000000         0.000000   
25%         6.067024           64.666932          0.000000         0.000000   
50%         8.113447           74.893237          2.000000         1.000000   
75%        10.068370           85.104610          3.000000         1.000000   
max        18.714738          100.000000          3.000000         1.000000   

       school_type  sports_participation  part_time_job     siblings  \
count  4750.000000           4750.000000    4750.000000  4750.000000   
mean      0.993263              1.504421       0.489053     2.032000   
std       0.813627              1.111343       0.499933     1.426602   
min       0.000000              0.000000       0.000000     0.000000   
25%       0.000000              1.000000       0.000000     1.000000   
50%       1.000000              2.000000       0.000000     2.000000   
75%       2.000000              2.000000       1.000000     3.000000   
max       2.000000              3.000000       1.000000     9.000000   

       commute_time_mins  favorite_subject  ...  screen_time_weekly  \
count        4750.000000       4750.000000  ...         4750.000000   
mean           30.460856          2.004421  ...           13.902894   
std            14.357631          1.414877  ...            5.998482   
min             5.000000          0.000000  ...            0.000000   
25%            20.185850          1.000000  ...            9.899414   
50%            29.999436          2.000000  ...           13.893609   
75%            40.205028          3.000000  ...           18.027138   
max            85.268616          4.000000  ...           34.499493   

         height_cm    weight_kg   lunch_type   math_tutor  reading_habit  \
count  4750.000000  4750.000000  4750.000000  4750.000000    4750.000000   
mean    160.070126    54.852794     0.987789     0.507158       1.507789   
std      11.884900    11.902029     0.820008     0.500001       1.109428   
min     130.000000    30.000000     0.000000     0.000000       0.000000   
25%     151.927614    46.584774     0.000000     0.000000       1.000000   
50%     159.997054    54.795697     1.000000     1.000000       1.000000   
75%     168.187011    63.084992     2.000000     1.000000       3.000000   
max     200.000000    96.824370     2.000000     1.000000       3.000000   

       video_game_freq  music_hours_weekly  parent_meeting_freq      uniform  
count      4750.000000         4750.000000          4750.000000  4750.000000  
mean          1.497474            5.047120             0.999579     0.504632  
std           1.109452            2.861449             0.813913     0.500031  
min           0.000000            0.000000             0.000000     0.000000  
25%           1.000000            2.997055             0.000000     0.000000  
50%           2.000000            5.031735             1.000000     1.000000  
75%           2.000000            7.043462             2.000000     1.000000  
max           3.000000           13.983962             2.000000     1.000000  

[8 rows x 25 columns]

In [21]:
#3
df_modified = df.copy()
df_modified["hours_studied_x2"] = df_modified["hours_studied"] * 2

df_modified.head()


hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...   height_cm  weight_kg  \
0          31.681382               2.0  ...  157.398274  53.055261   
1          19.423883               4.0  ...  151.295654  60.628213   
2          28.859972               0.0  ...  183.900640  65.655529   
3          40.083853               1.0  ...  164.835570  38.357323   
4          23.838820               2.0  ...  166.303604  39.271753   

   lunch_type  math_tutor  reading_habit  video_game_freq  music_hours_weekly  \
0         0.0         NaN            1.0              0.0            0.898032   
1         2.0         1.0            1.0              3.0            3.291397   
2         0.0         1.0            0.0              1.0            0.000000   
3         2.0         1.0            2.0              1.0            2.410233   
4         NaN         0.0            1.0              2.0            1.200275   

   parent_meeting_freq  uniform  hours_studied_x2  
0                  1.0      1.0          9.486216  
1                  0.0      0.0         21.984073  
2                  2.0      1.0         17.697871  
3                  0.0      0.0          6.962232  
4                  1.0      1.0         12.528398  

[5 rows x 26 columns]

In [14]:
#4
df.iloc[0:5, 0:3]


hours_studied  attendance_percent  parent_education
0       4.743108           79.781453               3.0
1      10.992036           97.666558               3.0
2       8.848935           57.950598               2.0
3       3.481116           84.636899               0.0
4       6.264199           58.081774               1.0

In [22]:
#5
df_filled = df.fillna(df.median(numeric_only=True))

df_filled.head()


hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              1.0   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          1.0                   1.0            0.0       4.0   
1          0.0                   3.0            0.0       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
0          31.681382               2.0  ...            2.339672  157.398274   
1          19.423883               4.0  ...           13.893609  151.295654   
2          28.859972               0.0  ...           16.989369  183.900640   
3          40.083853               1.0  ...           11.631093  164.835570   
4          23.838820               2.0  ...           15.372885  166.303604   

   weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
0  53.055261         0.0         1.0            1.0              0.0   
1  60.628213         2.0         1.0            1.0              3.0   
2  65.655529         0.0         1.0            0.0              1.0   
3  38.357323         2.0         1.0            2.0              1.0   
4  39.271753         1.0         0.0            1.0              2.0   

   music_hours_weekly  parent_meeting_freq  uniform  
0            0.898032                  1.0      1.0  
1            3.291397                  0.0      0.0  
2            0.000000                  2.0      1.0  
3            2.410233                  0.0      0.0  
4            1.200275                  1.0      1.0  

[5 rows x 25 columns]

In [24]:
#6
df_drop_col = df.drop(columns=["uniform"])
df_drop_col.head()
df_drop_rows = df.dropna()
df_drop_rows.head()


hours_studied  attendance_percent  parent_education  internet_access  \
3        3.481116           84.636899               0.0              0.0   
7        6.713262           63.990601               1.0              1.0   
8       11.797809           84.437431               3.0              1.0   
10       5.963342           54.191108               0.0              1.0   
12      12.474169           95.368739               3.0              1.0   

    school_type  sports_participation  part_time_job  siblings  \
3           0.0                   2.0            0.0       4.0   
7           2.0                   2.0            0.0       3.0   
8           0.0                   1.0            0.0       0.0   
10          0.0                   3.0            1.0       2.0   
12          0.0                   0.0            0.0       6.0   

    commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
3           40.083853               1.0  ...           11.631093  164.835570   
7           30.064064               2.0  ...           13.058085  166.310626   
8           15.620543               1.0  ...            8.101199  155.137833   
10          38.159836               1.0  ...           14.096965  161.629177   
12          29.310399               2.0  ...            7.912026  151.538063   

    weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
3   38.357323         2.0         1.0            2.0              1.0   
7   65.876931         2.0         1.0            0.0              0.0   
8   46.922817         0.0         1.0            1.0              1.0   
10  42.016934         2.0         0.0            3.0              2.0   
12  60.879209         1.0         0.0            3.0              0.0   

    music_hours_weekly  parent_meeting_freq  uniform  
3             2.410233                  0.0      0.0  
7            12.024411                  2.0      1.0  
8             5.892455                  2.0      1.0  
10            6.570614                  1.0      0.0  
12            2.903802                  0.0      1.0  

[5 rows x 25 columns]

In [25]:
#7
df_filtered = df[df["favorite_subject"].astype(str).str.startswith("1")]

df_filtered.head()



hours_studied  attendance_percent  parent_education  internet_access  \
3        3.481116           84.636899               0.0              0.0   
8       11.797809           84.437431               3.0              1.0   
10       5.963342           54.191108               0.0              1.0   
11       7.715873           55.539041               0.0              0.0   
13       6.083294           51.081407               3.0              0.0   

    school_type  sports_participation  part_time_job  siblings  \
3           0.0                   2.0            0.0       4.0   
8           0.0                   1.0            0.0       0.0   
10          0.0                   3.0            1.0       2.0   
11          1.0                   0.0            1.0       5.0   
13          0.0                   2.0            1.0       2.0   

    commute_time_mins  favorite_subject  ...  screen_time_weekly   height_cm  \
3           40.083853               1.0  ...           11.631093  164.835570   
8           15.620543               1.0  ...            8.101199  155.137833   
10          38.159836               1.0  ...           14.096965  161.629177   
11           5.000000               1.0  ...           14.827132  156.872729   
13          12.474610               1.0  ...           12.067095  159.410046   

    weight_kg  lunch_type  math_tutor  reading_habit  video_game_freq  \
3   38.357323         2.0         1.0            2.0              1.0   
8   46.922817         0.0         1.0            1.0              1.0   
10  42.016934         2.0         0.0            3.0              2.0   
11  48.955959         0.0         1.0            NaN              3.0   
13  58.070936         1.0         1.0            2.0              0.0   

    music_hours_weekly  parent_meeting_freq  uniform  
3             2.410233                  0.0      0.0  
8             5.892455                  2.0      1.0  
10            6.570614                  1.0      0.0  
11            7.549924                  1.0      1.0  
13            6.055819                  0.0      0.0  

[5 rows x 25 columns]

In [26]:
#8
df_engineered = df.copy()
df_engineered["study_effectiveness"] = (
    df_engineered["hours_studied"] * df_engineered["attendance_percent"]
)

df_engineered.head()


hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0            NaN       1.0   
2          0.0                   1.0            0.0       3.0   
3          0.0                   2.0            0.0       4.0   
4          0.0                   3.0            1.0       2.0   

   commute_time_mins  favorite_subject  ...   height_cm  weight_kg  \
0          31.681382               2.0  ...  157.398274  53.055261   
1          19.423883               4.0  ...  151.295654  60.628213   
2          28.859972               0.0  ...  183.900640  65.655529   
3          40.083853               1.0  ...  164.835570  38.357323   
4          23.838820               2.0  ...  166.303604  39.271753   

   lunch_type  math_tutor  reading_habit  video_game_freq  music_hours_weekly  \
0         0.0         NaN            1.0              0.0            0.898032   
1         2.0         1.0            1.0              3.0            3.291397   
2         0.0         1.0            0.0              1.0            0.000000   
3         2.0         1.0            2.0              1.0            2.410233   
4         NaN         0.0            1.0              2.0            1.200275   

   parent_meeting_freq  uniform  study_effectiveness  
0                  1.0      1.0           378.412061  
1                  0.0      0.0          1073.554356  
2                  2.0      1.0           512.801107  
3                  0.0      0.0           294.630850  
4                  1.0      1.0           363.835804  

[5 rows x 26 columns]