<a href="https://colab.research.google.com/github/avinandhajs/Judge_It_Well/blob/main/Copy_of_Assignment_0(Basic_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [9]:
##Q.1.1
import numpy as np
array1 = np.array([0]*10)
print(array1)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
##Q.1.2
array2 = np.array([5]*10)
print(array2)

[5 5 5 5 5 5 5 5 5 5]


In [11]:
##Q.1.3
array3 = np.arange(9).reshape(3, 3)
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
##Q.1.4
number = np.random.rand()
print(number)

0.005900763927835673


In [13]:
##Q.1.5
array4 = np.linspace(0, 1, 20, endpoint=False)
print(array4)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [14]:
##Q.1.6
n_of_vowel = 0
s = input("ENTER THE STRING : ")
for letter in s.lower():
  if letter in ['a','e','i','o','u']:
    n_of_vowel += 1
print(n_of_vowel)

ENTER THE STRING : Watermelon
4


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [15]:
##Q.2.1
import numpy as np
numbers = np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even_num = numbers[numbers%2 == 0]
print(even_num)

[ 12  44 102  -8  56  90 -24  48]


In [16]:
##Q.2.2
array5 =  np.random.randint(10,100,(5,4))
print(array2)

[5 5 5 5 5 5 5 5 5 5]


In [17]:
##Q.2.3
#taking the 3X3 matrix from the Q.1.3
matrix = array3
array6 = matrix[0:3,0:2]
print(array6)

[[0 1]
 [3 4]
 [6 7]]


In [18]:
##Q.2.4
array7 = np.random.randint(0,100,20) # 1D array
array7 = array7.reshape(4,5) #reshaped into 2D array
print(array7)

[[27 12 73 69 71]
 [ 2  9  6 69 81]
 [29 17  2 39 68]
 [81 44 41 25 43]]


In [19]:
##Q.2.5
#let array7 be our 2D array from the previous question
array8 = array7.reshape(1,20)
print(array8)

[[27 12 73 69 71  2  9  6 69 81 29 17  2 39 68 81 44 41 25 43]]


In [20]:
##Q.2.6
matrix1 = np.random.randint(0,100,9).reshape(3,3)
matrix2 = np.random.randint(0,100,15).reshape(3,5)
matrix3 = np.array([0]*15).reshape(3,5)
for i in range(0,3):
  for j in range(0,5):
    for k in range(0,3):
      matrix3[i][j] = matrix3[i][j] + (matrix1[i][k])*(matrix2[k][j])
print(matrix1)
print(matrix2)
print(matrix3)

[[40 22 46]
 [59 61 66]
 [ 3 44 55]]
[[33 69 18 34  9]
 [53 41 77 37 67]
 [66 99  4 74 30]]
[[ 5522  8216  2598  5578  3214]
 [ 9536 13106  6023  9147  6598]
 [ 6061  7456  3662  5800  4625]]


**Q.3**

(i) Check if matrix multiplication is valid

In [21]:
##Q.3.(i)
rol1,col1 = matrix1.shape
rol2,col2 = matrix2.shape
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


(ii) Using loops (without using numpy)

In [22]:
##Q.3.(ii)
col1 = 0
rol2 = 0
for ele in matrix1[0]:
  col1 += 1
for ele in matrix2:
  rol2 += 1
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


**Q.4**
(i) Given:

In [24]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [23]:
##Q.4.1
s = 0
X = [1,2,3,4,5]
for i in X:
  s += i
meanx = s/len(X)
print(f"The mean of X is = {meanx}")

The mean of X is = 3.0


In [5]:
##Q.4.2
s = 0
y = [2,4,5,4,5]
for i in y:
  s += i
meany = s/len(y)
print(f"The mean of X is = {meany}")

The mean of X is = 4.0


In [25]:
##Q.4.3
# let m be the slope
cf1 = ([0]*100)
y = [2,4,5,4,5]
X = [1,2,3,4,5]
num = den = 0
for i in range(0,5):
  num += (meanx - X[i])*(meany - y[i])
  den += (meanx - X[i])**2
m = num/den
print(f"Slope is = {m}")

Slope is = 0.6


In [8]:
#Q.4.4
c = meany - m * meanx
print(f"The y intercept = {c}")

The y intercept = 2.2


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).