**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [1]:
import numpy as np

# 1.
array_of_zeros = np.zeros(10)
print(f"Array of 10 zeros: {array_of_zeros}")

# 2.
array_of_fives = np.full(10, 5)
print(f"Array of 10 fives: {array_of_fives}")

# 3.
matrix_0_to_8 = np.arange(0, 9).reshape(3, 3)
print(f"\n3x3 matrix (0-8):\n{matrix_0_to_8}")

# 4.
random_number = np.random.rand()
print(f"\nRandom number between 0 and 1: {random_number}")

# 5.
linspace_array = np.linspace(0, 1, 20)
print(f"\n20 linearly spaced points between 0 and 1: {linspace_array}")

# 6.
def count_vowels(input_string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in input_string:
        if char in vowels:
            count += 1
    return count

my_string = "Hello, World! This is a test string."
vowel_count = count_vowels(my_string)
print(f"\nNumber of vowels in '{my_string}': {vowel_count}")

my_string_2 = "Python Programming"
vowel_count_2 = count_vowels(my_string_2)
print(f"Number of vowels in '{my_string_2}': {vowel_count_2}")

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]

3x3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Random number between 0 and 1: 0.9154338391256365

20 linearly spaced points between 0 and 1: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Number of vowels in 'Hello, World! This is a test string.': 8
Number of vowels in 'Python Programming': 4


In [ ]:
#Q.1.2
.....

**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [2]:
import numpy as np

# 1.
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
even_numbers = [num for num in numbers if num % 2 == 0]
print(f"Original array: {numbers}")
print(f"Even numbers: {even_numbers}")

# 2.
random_2d_array = np.random.randint(10, 101, size=(5, 4))
print(f"\n2D array (5x4) with random integers (10-100):\n{random_2d_array}")

# 3.
subarray = random_2d_array[0:3, 0:2]
print(f"\n3x2 subarray (first three rows, first two columns):\n{subarray}")

# 4.
# Let's create a 1D array with 20 elements for reshaping into 4x5
one_d_array = np.arange(20) # Example 1D array from 0 to 19
reshaped_2d_array = one_d_array.reshape(4, 5)
print(f"\nOriginal 1D array: {one_d_array}")
print(f"Reshaped 2D array (4x5):\n{reshaped_2d_array}")

# 5.
flattened_array = reshaped_2d_array.flatten()
print(f"\nFlattened 1D array: {flattened_array}")

# 6.
# Generate a second random 2D array for multiplication. For a 4x5 matrix, the second must be 5xN.
matrix1 = reshaped_2d_array # Our 4x5 array
matrix2 = np.random.randint(1, 10, size=(5, 3)) # A 5x3 random matrix

matrix_product = np.dot(matrix1, matrix2)
print(f"\nMatrix 1 (4x5):\n{matrix1}")
print(f"\nMatrix 2 (5x3):\n{matrix2}")
print(f"\nMatrix product (4x3):\n{matrix_product}")

Original array: [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
Even numbers: [12, 44, 102, -8, 56, 90, -24, 48]

2D array (5x4) with random integers (10-100):
[[41 81 73 92]
 [89 17 39 34]
 [98 88 46 88]
 [45 17 11 81]
 [80 58 39 62]]

3x2 subarray (first three rows, first two columns):
[[41 81]
 [89 17]
 [98 88]]

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped 2D array (4x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Flattened 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Matrix 1 (4x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Matrix 2 (5x3):
[[2 5 6]
 [6 1 3]
 [9 3 4]
 [9 4 5]
 [6 5 4]]

Matrix product (4x3):
[[ 75  39  42]
 [235 129 152]
 [395 219 262]
 [555 309 372]]


**Q.3**

(i) Check if matrix multiplication is valid

In [3]:
def are_matrices_multipliable(matrix1, matrix2):
    # Number of columns in matrix1
    cols1 = len(matrix1[0])
    # Number of rows in matrix2
    rows2 = len(matrix2)

    if cols1 == rows2:
        return True
    else:
        return False

# Example usage:
# Valid multiplication (4x5 and 5x3 from previous output)
matrix1_example = [[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9],
                   [10, 11, 12, 13, 14],
                   [15, 16, 17, 18, 19]] # 4 rows, 5 columns

matrix2_example = [[2, 5, 6],
                   [6, 1, 3],
                   [9, 3, 4],
                   [9, 4, 5],
                   [6, 5, 4]] # 5 rows, 3 columns

print(f"Matrix 1 (dimensions: {len(matrix1_example)}x{len(matrix1_example[0])}):\n{matrix1_example}")
print(f"Matrix 2 (dimensions: {len(matrix2_example)}x{len(matrix2_example[0])}):\n{matrix2_example}")
print(f"Can these matrices be multiplied? {are_matrices_multipliable(matrix1_example, matrix2_example)}")

# Invalid multiplication example
invalid_matrix = [[1, 2],
                    [3, 4]] # 2 rows, 2 columns

print(f"\nMatrix 1 (dimensions: {len(matrix1_example)}x{len(matrix1_example[0])}):\n{matrix1_example}")
print(f"Invalid Matrix (dimensions: {len(invalid_matrix)}x{len(invalid_matrix[0])}):\n{invalid_matrix}")
print(f"Can these matrices be multiplied? {are_matrices_multipliable(matrix1_example, invalid_matrix)}")

Matrix 1 (dimensions: 4x5):
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]
Matrix 2 (dimensions: 5x3):
[[2, 5, 6], [6, 1, 3], [9, 3, 4], [9, 4, 5], [6, 5, 4]]
Can these matrices be multiplied? True

Matrix 1 (dimensions: 4x5):
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]
Invalid Matrix (dimensions: 2x2):
[[1, 2], [3, 4]]
Can these matrices be multiplied? False


(ii) Using loops (without using numpy)

In [4]:
def multiply_matrices_without_numpy(matrix1, matrix2):
    # Get dimensions of matrix1 (rows1 x cols1)
    rows1 = len(matrix1)
    cols1 = len(matrix1[0])

    # Get dimensions of matrix2 (rows2 x cols2)
    rows2 = len(matrix2)
    cols2 = len(matrix2[0])

    # Check if multiplication is possible
    if cols1 != rows2:
        return "Error: Number of columns in the first matrix must equal the number of rows in the second matrix."

    # Initialize the result matrix with zeros
    # The result matrix will have dimensions (rows1 x cols2)
    result_matrix = [[0 for _ in range(cols2)] for _ in range(rows1)]

    # Perform matrix multiplication using nested loops
    for i in range(rows1):          # Iterate over rows of matrix1
        for j in range(cols2):      # Iterate over columns of matrix2
            for k in range(cols1):  # Iterate over columns of matrix1 (or rows of matrix2)
                result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]

    return result_matrix

# Example usage with valid matrices (from previous Q.2 output, matrix1 and matrix2 are already defined as lists of lists)
matrix1_example_ll = [[0, 1, 2, 3, 4],
                        [5, 6, 7, 8, 9],
                        [10, 11, 12, 13, 14],
                        [15, 16, 17, 18, 19]] # 4x5

matrix2_example_ll = [[2, 5, 6],
                        [6, 1, 3],
                        [9, 3, 4],
                        [9, 4, 5],
                        [6, 5, 4]] # 5x3

print(f"Matrix 1 (4x5):\n{matrix1_example_ll}")
print(f"\nMatrix 2 (5x3):\n{matrix2_example_ll}")

product = multiply_matrices_without_numpy(matrix1_example_ll, matrix2_example_ll)
print(f"\nMatrix product (using loops):\n{product}")

# Example with invalid matrices
invalid_matrix_ll = [[1, 2],
                       [3, 4]] # 2x2

print(f"\nMatrix 1 (4x5):\n{matrix1_example_ll}")
print(f"\nInvalid Matrix (2x2):\n{invalid_matrix_ll}")

product_invalid = multiply_matrices_without_numpy(matrix1_example_ll, invalid_matrix_ll)
print(f"\nAttempted multiplication with invalid dimensions: {product_invalid}")

Matrix 1 (4x5):
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

Matrix 2 (5x3):
[[2, 5, 6], [6, 1, 3], [9, 3, 4], [9, 4, 5], [6, 5, 4]]

Matrix product (using loops):
[[75, 39, 42], [235, 129, 152], [395, 219, 262], [555, 309, 372]]

Matrix 1 (4x5):
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

Invalid Matrix (2x2):
[[1, 2], [3, 4]]

Attempted multiplication with invalid dimensions: Error: Number of columns in the first matrix must equal the number of rows in the second matrix.


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).